/**
 * SyncService - Comprehensive Project Sync
 *
 * Handles ALL sync operations in a single TypeScript execution:
 * - Git analysis
 * - Project stats
 * - Native skill generation
 * - State updates
 *
 * This eliminates the need for Claude to make 50+ individual tool calls.
 * Instead, one command does everything.
 *
 * Analysis/stats functions extracted to ./sync-analyzer.ts
 *
 */

import fs from 'node:fs/promises'
import path from 'node:path'
import { setupMcpServers } from '../commands/setup/mcp'
import { indexProject as indexBm25, updateProjectIndex as updateBm25 } from '../domain/bm25'
import { indexCoChanges } from '../domain/git-cochange'
import { indexImports, updateImportGraph } from '../domain/import-graph'
import { indexSymbols, updateSymbols } from '../domain/symbol-graph'
import { getErrorMessage } from '../errors'
import { detectCodex, getActiveProvider } from '../infrastructure/ai-provider'
import { verifyCodexPRouterReady } from '../infrastructure/codex-skill'
import commandInstaller from '../infrastructure/command-installer'
import configManager from '../infrastructure/config-manager'
import pathManager from '../infrastructure/path-manager'
import { analysisStorage } from '../storage/analysis-storage'
import type { ProjectSyncResult, SyncMetrics, SyncOptions } from '../types/project-sync'
import type { Context7Status } from '../types/services.js'
import type { VerificationReport } from '../types/sync-verifier'
import { readJson } from '../utils/file-helper'
import log from '../utils/logger'
import {
  bootstrapCodeGraphFromArtifact,
  maybeExportAfterIndex,
  shouldAutoUploadCodeGraph,
} from './code-graph-artifact'
import { repairContextQuality } from './context-quality-service'
import context7Service from './context7-service'
import { skillGenerator } from './skill-generator'
import { emptyCommands, emptyGitData, emptyStack, emptyStats } from './sync/defaults'
import { detectIncrementalChanges } from './sync/incremental'
import { archiveStaleData, recordSyncMetrics, saveDraftAnalysis } from './sync/persistence'
import {
  runSyncPhase,
  type SyncPhaseTiming,
  withPhaseTimeout as withTimeout,
} from './sync/phase-runner'
import { type PostIndexWork, startPostIndexWork } from './sync/post-index'
import {
  ensureProjectDirectories,
  logSyncEvent,
  updateProjectDoc,
  updateStateDoc,
} from './sync/state-update'
import { analyzeGit, detectCommands, detectStack, gatherStats } from './sync-analyzer'
import { syncVerifier } from './sync-verifier'
import { publishWorkCostSnapshots } from './work-cost-service'

// SYNC SERVICE

class SyncService {
  private projectPath: string
  private projectId: string | null = null
  private globalPath: string = ''
  private cliVersion: string = '0.0.0'

  constructor() {
    this.projectPath = process.cwd()
  }

  /**
   * Main sync method - does everything in one call
   */
  async sync(
    projectPath: string = process.cwd(),
    options: SyncOptions = {}
  ): Promise<ProjectSyncResult> {
    this.projectPath = projectPath
    const startTime = Date.now()
    const phaseTimings: SyncPhaseTiming[] = []
    const phase = <T>(name: string, fn: () => Promise<T>): Promise<T> =>
      runSyncPhase(name, fn, phaseTimings)

    const context7Status: Context7Status = {
      installed: false,
      verified: false,
      configPath: '',
      message: '',
    }
    const postIndexWork: PostIndexWork[] = []

    try {
      // 1. Get project config
      this.projectId = await configManager.getProjectId(projectPath)
      if (!this.projectId) {
        return {
          success: false,
          projectId: '',
          cliVersion: '',
          git: emptyGitData(),
          stats: emptyStats(),
          commands: emptyCommands(),
          stack: emptyStack(),
          context7: { installed: false, verified: false },
          error: 'No prjct project. Run p. init first.',
        }
      }

      this.globalPath = pathManager.getGlobalProjectPath(this.projectId)
      this.cliVersion = await this.getCliVersion()

      // One-time, lossless upgrade: mutable policy belongs in prjct's global
      // project store. The client file is normalized to its stable locator.
      await phase('project-settings-migration', () =>
        configManager.migrateLegacyProjectSettings(projectPath)
      )

      // Cleanup legacy agent files generated by prjct (replaced by skills)
      await fs
        .rm(path.join(this.globalPath, 'agents'), { recursive: true, force: true })
        .catch(() => {})

      // Codex router check — non-blocking, sync should succeed for other providers
      const codexDetection = await detectCodex()
      if (codexDetection.installed) {
        const codexRouter = await verifyCodexPRouterReady({ autoRepair: true })
        if (!codexRouter.verified) {
          log.warn(`Codex p. router not ready: ${codexRouter.message || 'verification failed'}`)
        }
      }

      // Keep prjct-managed MCP defaults self-healing from sync as well as setup.
      await phase('mcp-defaults', () => setupMcpServers({ silent: true, verifyContext7: false }))

      // Context7 is best-effort, never a hard gate, and provider-aware: it
      // configures into the ACTIVE harness's MCP config (Claude → mcp.json,
      // Codex → config.toml). Its smoke check needs network, so a hard failure
      // here used to abort sync entirely for Codex/Gemini and any sandboxed/
      // offline run — even though indexing, memory and vault regen don't depend
      // on it. Mirror the Codex-router check above: try, warn on failure, keep
      // going. `verified:false` still surfaces so `prjct start`/setup can repair.
      const activeProvider = await getActiveProvider().catch(() => null)
      const context7Provider = activeProvider?.name ?? 'claude'
      try {
        Object.assign(
          context7Status,
          await phase('context7', () => context7Service.ensureReady(context7Provider))
        )
      } catch (error) {
        const message = getErrorMessage(error)
        log.warn(`Context7 MCP not ready (continuing sync): ${message}`)
        Object.assign(context7Status, {
          verified: false,
          message,
        })
      }

      // 2. Ensure directories exist (non-blocking)
      const ensureDirsPromise = ensureProjectDirectories(this.globalPath)
      await ensureDirsPromise

      // The pre-v1.24.1 JSON→SQLite migration (`migrate-json`) was retired
      // here — it was slated for v3.0 removal and every active install migrated
      // long ago. The pre-v2.19.7 crew-disk sweep below is a separate concern
      // (kv_store CHECKPOINTS/team.json) and stays.

      // 2d. Client-tree hygiene (HARD LAW): only `.prjct/prjct.config.json`
      // may remain in the customer worktree. Everything else is migrated to
      // project SQLite then DELETED (CHECKPOINTS.md, team.json, sessions/,
      // audits/, deploy/, any other junk). Set PRJCT_SKIP_CREW_SWEEP=1 to skip.
      if (process.env.PRJCT_SKIP_CREW_SWEEP !== '1') {
        await phase('legacy-crew-sweep', async () => {
          try {
            const { legacyCrewSweep } = await import('./legacy-crew-sweep')
            const result = await legacyCrewSweep(this.projectPath, this.projectId!)
            if (
              result.checkpointsMigrated ||
              result.teamMigrated ||
              result.checkpointsHandEditWarned ||
              result.teamHandEditWarned ||
              result.ghostDirsPurged.length > 0 ||
              result.clientPrjctJunkPurged.length > 0 ||
              result.errors.length > 0
            ) {
              log.info('Legacy crew sweep ran', {
                checkpointsMigrated: result.checkpointsMigrated,
                teamMigrated: result.teamMigrated,
                checkpointsHandEditWarned: result.checkpointsHandEditWarned,
                teamHandEditWarned: result.teamHandEditWarned,
                ghostDirsPurged: result.ghostDirsPurged,
                ghostFilesIngested: result.ghostFilesIngested,
                clientPrjctJunkPurged: result.clientPrjctJunkPurged,
                errors: result.errors.length,
              })
            }
          } catch (error) {
            log.debug('Legacy crew sweep failed (non-critical)', {
              error: getErrorMessage(error),
            })
          }
        })
      }

      // 3. Gather all data IN PARALLEL (30-50% speedup)
      // These operations are independent and can run concurrently
      const [git, stats, commands, stack] = await phase('gather', () =>
        withTimeout(
          Promise.all([
            analyzeGit(this.projectPath),
            gatherStats(this.projectPath),
            detectCommands(this.projectPath),
            detectStack(this.projectPath),
          ]),
          'gather'
        )
      )

      // 3a. Incremental change detection — see ./sync/incremental.ts for the
      // hash-based diff + import-graph propagation.
      const {
        shouldRebuildIndexes,
        changedDomains: _changedDomains,
        incrementalInfo,
        changedSourceFiles,
        deletedSourceFiles,
      } = await phase('incremental', () =>
        detectIncrementalChanges({
          projectId: this.projectId!,
          projectPath: this.projectPath,
          isFullSync: options.full === true,
          changedFilesHint: options.changedFiles,
        })
      )

      // 3a. Dynamic file inventory EVERY sync (extensions/languages in THIS tree).
      // Work-scope uses this instead of hard-coded language lists.
      try {
        const { refreshFileInventory } = await import('./project-file-inventory')
        await refreshFileInventory(this.projectId!, this.projectPath)
      } catch {
        /* non-critical — scope falls back to open accept until next sync */
      }

      // 3a-bis. Bootstrap symbol graph from per-project cache (~/.prjct-cli/projects/<id>/)
      // if SQLite symbol tables empty — never reads from the client repo.
      try {
        await bootstrapCodeGraphFromArtifact(this.projectId!)
      } catch {
        /* non-critical */
      }

      // 3b. Build file-ranking indexes IN PARALLEL (BM25, symbols, import graph, co-change)
      // Skip if no source files changed (incremental optimization)
      if (shouldRebuildIndexes) {
        await phase('index', async () => {
          try {
            const canUseIncrementalIndexes =
              incrementalInfo?.isIncremental &&
              (changedSourceFiles.length > 0 || deletedSourceFiles.length > 0)
            await Promise.all([
              canUseIncrementalIndexes
                ? updateBm25(
                    this.projectPath,
                    this.projectId!,
                    changedSourceFiles,
                    deletedSourceFiles
                  )
                : indexBm25(this.projectPath, this.projectId!),
              canUseIncrementalIndexes
                ? updateImportGraph(
                    this.projectPath,
                    this.projectId!,
                    changedSourceFiles,
                    deletedSourceFiles
                  )
                : indexImports(this.projectPath, this.projectId!),
              canUseIncrementalIndexes
                ? updateSymbols(
                    this.projectPath,
                    this.projectId!,
                    changedSourceFiles,
                    deletedSourceFiles
                  )
                : indexSymbols(this.projectPath, this.projectId!),
              indexCoChanges(this.projectPath, this.projectId!),
            ])
            // Start local artifact refresh + optional cloud upload now, then
            // overlap it with the remaining independent sync phases.
            const postIndexProjectId = this.projectId!
            const postIndexProjectPath = this.projectPath
            const postIndexConfig = await configManager
              .readConfig(postIndexProjectPath)
              .catch(() => null)
            const uploadToCloud = shouldAutoUploadCodeGraph(postIndexConfig)
            postIndexWork.push(
              startPostIndexWork(
                () => maybeExportAfterIndex(postIndexProjectId, { uploadToCloud }),
                {
                  onComplete: ({ totalMs, error }) => {
                    log.debug('sync post-index work settled', {
                      projectId: postIndexProjectId,
                      uploadToCloud,
                      totalMs,
                      ...(error === undefined ? {} : { error: getErrorMessage(error) }),
                    })
                  },
                }
              )
            )
          } catch (error) {
            log.debug('File ranking index build failed (non-critical)', {
              error: getErrorMessage(error),
            })
          }
        })
      }

      // 4. Portable multi-host skills (no project stamp — L0 isolation)
      const skillPhaseStart = Date.now()
      log.debug('sync phase start', { phase: 'skills' })
      const generatedSkills = await skillGenerator.generateAndInstall().catch((error) => {
        log.debug('Native skill generation failed (non-critical)', {
          error: getErrorMessage(error),
        })
        return undefined
      })
      log.debug('sync phase done', { phase: 'skills', ms: Date.now() - skillPhaseStart })

      // 5. Update files IN PARALLEL (write to different files)
      await phase('update-files', () =>
        Promise.all([
          updateProjectDoc({
            projectId: this.projectId!,
            projectPath: this.projectPath,
            cliVersion: this.cliVersion,
            git,
            stats,
          }),
          updateStateDoc({
            projectId: this.projectId!,
            projectPath: this.projectPath,
            stats,
            stack,
          }),
          Promise.resolve(logSyncEvent(this.projectId!, git, stats)),
          saveDraftAnalysis(
            this.projectId!,
            this.projectPath,
            git,
            stats,
            stack,
            context7Status.verified
          ),
        ])
      )

      const activeAnalysis = await analysisStorage.getActive(this.projectId)
      const analysisSummary = {
        patterns: activeAnalysis?.patterns?.length || 0,
        antiPatterns: activeAnalysis?.antiPatterns?.length || 0,
        criticalAntiPatterns:
          activeAnalysis?.antiPatterns?.filter((a) => a.severity === 'high').length || 0,
      }

      // 9a. Project style model — recalculate every sync (dual evolution with
      // developer snapshot captured by the floating metrics phase below).
      // Progressive delta + history + memory bridge.
      const projectStyle: import('../types/project-sync').ProjectStyleSyncSummary | undefined =
        await (async () => {
          try {
            const { recomputeProjectStyle, formatProjectStyleForSync } = await import(
              './project-style-evolution'
            )
            const styleResult = await phase('project-style', () =>
              recomputeProjectStyle({
                projectId: this.projectId!,
                projectPath: this.projectPath,
                stats,
                stack,
                commands,
                commitHash: git.recentCommits[0]?.hash ?? null,
                source: 'sync-mechanical',
              })
            )
            const formatted = formatProjectStyleForSync(styleResult)
            const coverageRaw = styleResult.snapshot.payload.metrics.styleCoverage
            return {
              summary: styleResult.snapshot.summary,
              evolutionMd: formatted.evolutionMd,
              patternCount: styleResult.snapshot.patternCount,
              antiPatternCount: styleResult.snapshot.antiPatternCount,
              conventionCount: styleResult.snapshot.conventionCount,
              styleCoverage:
                typeof coverageRaw === 'number' ? coverageRaw : Number(coverageRaw) || 0,
              isFirst: styleResult.isFirst,
              hasChanges: styleResult.delta.hasChanges,
            }
          } catch (error) {
            log.debug('Project style recompute failed (non-critical)', {
              error: getErrorMessage(error),
            })
            return undefined
          }
        })()

      // Kept sequential on purpose: archive deletes rows from the same
      // tasks/memory tables work-cost and context-quality READ, so running
      // them concurrently would race against rows mid-deletion. Don't
      // parallelize this — the current order is correct, not accidental.
      //
      // The phases launched below are different: install-global,
      // install-agent-surfaces and verify only touch global config files /
      // project markdown surfaces / run checks — never the project SQLite —
      // and recordSyncMetrics only READS the tables archive mutates (its
      // writes land in metrics / velocity_sprints /
      // developer_profile_snapshots). They start now as floating work
      // (same pattern as startPostIndexWork at the index phase) and settle
      // after the retention chain. Failures are absorbed into debug
      // telemetry by startPostIndexWork — never an unhandled rejection in
      // the long-lived daemon. Each phase still records its own honest
      // wall-clock timing via runSyncPhase; the settlement log marks them
      // `overlapped: true` so they aren't mistaken for sequential time.
      const floatingWork: PostIndexWork[] = []
      const floatingResults: {
        syncMetrics?: SyncMetrics & { developerSnapshotCaptured?: boolean }
        verification?: VerificationReport
      } = {}
      const floatPhase = <T>(
        name: string,
        run: () => Promise<T>,
        onSettled: (result: T) => void
      ): void => {
        floatingWork.push(
          startPostIndexWork(
            async () => {
              onSettled(await phase(name, run))
            },
            {
              onComplete: ({ totalMs, error }) => {
                log.debug('sync floating phase settled', {
                  phase: name,
                  overlapped: true,
                  totalMs,
                  ...(error === undefined ? {} : { error: getErrorMessage(error) }),
                })
              },
            }
          )
        )
      }

      // 9. Record metrics for value dashboard — overlaps the chain below.
      const duration = Date.now() - startTime
      floatPhase(
        'metrics',
        () => recordSyncMetrics(this.projectId!, stats, duration),
        (result) => {
          floatingResults.syncMetrics = result
        }
      )

      // 10. Update global config and commands (CLI does EVERYTHING)
      // This ensures `prjct sync` from terminal updates global CLAUDE.md and
      // commands. The provider resolved at the top of sync is threaded down
      // so the install skips a redundant `<cli> --version` re-detection.
      floatPhase(
        'install-global',
        async () => {
          await commandInstaller.installGlobalConfig(activeProvider ?? undefined)
          await commandInstaller.syncCommands(activeProvider ?? undefined)
        },
        () => {}
      )

      // 11. Run verification checks (built-in + custom from config)
      floatPhase(
        'verify',
        async (): Promise<VerificationReport | undefined> => {
          try {
            const localConfig = await configManager.readConfig(this.projectPath)
            return await syncVerifier.verify(
              this.projectPath,
              this.globalPath,
              localConfig?.verification
            )
          } catch (error) {
            log.debug('Verification failed (non-critical)', { error: getErrorMessage(error) })
            return undefined
          }
        },
        (result) => {
          floatingResults.verification = result
        }
      )

      const workCost = await phase('work-cost', () => publishWorkCostSnapshots(this.projectId!))
      await phase('inference-cost', async () => {
        const { publishInferenceCostSnapshots } = await import('./inference-cost')
        return publishInferenceCostSnapshots(this.projectId!)
      })

      // 9b. Archive stale data (PRJ-267)
      await phase('archive', () => archiveStaleData(this.projectId!))

      // 9c. Context quality cleanup — repair historical generated junk from
      // older versions so sync leaves the second-brain read model usable.
      const contextQuality = await phase('context-quality', () =>
        repairContextQuality(this.projectPath, this.projectId!)
      )

      // 9d. Value-based retention (score → archive/delete). Default applies
      // capped actions; config.retention.mode = dry-run|off for observe/skip.
      // 9e. Inbox triage merges fingerprint duplicates + archives stale inbox.
      const retentionDryRun = await phase('retention', async () => {
        try {
          const cfg = await configManager.readConfig(this.projectPath).catch(() => null)
          const mode = cfg?.retention?.mode ?? 'apply'
          if (mode === 'off') return undefined

          const dryRun = mode === 'dry-run'
          const { applyRetention, triageInbox } = await import('./retention')
          const applied = applyRetention(this.projectId!, {
            dryRun,
            maxArchive: cfg?.retention?.maxArchive,
            maxDelete: cfg?.retention?.maxDelete,
          })
          const { inboxMerged, inboxArchived } = dryRun
            ? { inboxMerged: 0, inboxArchived: 0 }
            : (() => {
                const triaged = triageInbox(this.projectId!)
                return { inboxMerged: triaged.merged, inboxArchived: triaged.archived }
              })()

          // Cold purge: vacuum soft-deleted, orphan events, old archives,
          // auto-source caps. This is where historical bloat actually dies.
          const { runVaultPurge, vaultHealth } = await import('./retention/purge')
          const purged = await runVaultPurge(this.projectId!, {
            projectPath: this.projectPath,
            dryRun,
            softDeletedPurgeDays: cfg?.retention?.softDeletedPurgeDays,
            archivePruneDays: cfg?.retention?.archivePruneDays,
            autoSourceMaxLive: cfg?.retention?.autoSourceMaxLive,
          })
          const health = vaultHealth(this.projectId!)

          return {
            evaluated: applied.evaluated,
            active: applied.active,
            archive: applied.wouldArchive,
            delete: applied.wouldDelete,
            archived: applied.archived,
            deleted: applied.deleted,
            inboxMerged,
            inboxArchived,
            dryRun,
            samples: applied.samples.map((s) => ({
              id: s.id,
              type: s.type,
              verdict: s.verdict,
              score: s.score,
              reasons: s.reasons,
              excess: s.excess,
            })),
            referenceSize: applied.referenceSize,
            vault: {
              ...health,
              softDeletedPurged: purged.softDeletedPurged,
              orphanEventsPurged: purged.orphanEventsPurged,
              archivesPruned: purged.archivesPruned,
              autoSourceTrimmed: purged.autoSourceTrimmed,
              distilledDiscarded: purged.distilledDiscarded,
              digestsWritten: purged.digestsWritten,
            },
          }
        } catch (error) {
          // Best-effort: a scoring/apply failure must never break sync.
          log.debug('retention phase failed', { error: getErrorMessage(error) })
          return undefined
        }
      })

      // Continuous understanding: mark drift refresh applied so SessionStart
      // stops permanent-stale banners after a world-model sync.
      if (
        process.env.PRJCT_WORLD_MODEL_REFRESH === '1' ||
        process.env.PRJCT_DRIFT_REFRESH === '1'
      ) {
        try {
          const { resolveUserPath } = await import('../infrastructure/user-home')
          const { markDriftRefreshApplied } = await import('./drift-refresh')
          const cliHome = process.env.PRJCT_CLI_HOME
            ? path.resolve(process.env.PRJCT_CLI_HOME)
            : resolveUserPath('.prjct-cli')
          markDriftRefreshApplied(cliHome)
        } catch {
          /* best-effort */
        }
      }

      // Settle all floating work — settlement absorbs failures, so a broken
      // global-config write or verify check can never reject here.
      await Promise.all([
        ...postIndexWork.map((work) => work.settle()),
        ...floatingWork.map((work) => work.settle()),
      ])

      const syncMetrics = floatingResults.syncMetrics
      const verification = floatingResults.verification
      const developerSnapshotCaptured = syncMetrics?.developerSnapshotCaptured === true

      return {
        success: true,
        projectId: this.projectId,
        cliVersion: this.cliVersion,
        git,
        stats,
        commands,
        stack,
        context7: {
          installed: context7Status.installed,
          verified: context7Status.verified,
          message: context7Status.message,
        },
        analysisSummary,
        contextQuality,
        retentionDryRun,
        syncMetrics,
        workCost,
        verification,
        incremental: incrementalInfo,
        projectStyle,
        developerSnapshotCaptured,
        generatedSkills,
        phaseTimings,
      }
    } catch (error) {
      return {
        success: false,
        projectId: this.projectId || '',
        cliVersion: this.cliVersion,
        git: emptyGitData(),
        stats: emptyStats(),
        commands: emptyCommands(),
        stack: emptyStack(),
        context7: {
          installed: context7Status.installed,
          verified: context7Status.verified,
          message: context7Status.message,
        },
        error: getErrorMessage(error),
      }
    }
  }

  // DIRECTORY SETUP

  // PROJECT.JSON UPDATE

  // STATE.JSON UPDATE

  // MEMORY LOGGING

  // METRICS RECORDING

  /**
   * Record sync metrics for the value dashboard
   *
   * Uses REAL token counts from the BM25 index (actual project tokens)
   * instead of estimates. filteredSize = agent context files that get
   * loaded into the AI conversation.
   */
  // DRAFT ANALYSIS (PRJ-263)

  /**
   * Save sync results as a draft analysis.
   * Preserves existing sealed analysis — only the draft is overwritten.
   * Incorporates task feedback from completed tasks (PRJ-272).
   */
  // ARCHIVAL (PRJ-267)

  private async getCliVersion(): Promise<string> {
    try {
      const pkgPath = path.join(__dirname, '..', '..', 'package.json')
      const pkg = await readJson<{ version?: string }>(pkgPath)
      return pkg?.version || '0.0.0'
    } catch (error) {
      log.debug('Failed to read CLI version', { error: getErrorMessage(error) })
      return '0.0.0'
    }
  }
}

export const syncService = new SyncService()
export { SyncService }
