/**
 * SyncService - Comprehensive Project Sync
 *
 * Handles ALL sync operations in a single TypeScript execution:
 * - Git analysis
 * - Project stats
 * - Native skill generation
 * - State updates
 *
 * This eliminates the need for Claude to make 50+ individual tool calls.
 * Instead, one command does everything.
 *
 * Analysis/stats functions extracted to ./sync-analyzer.ts
 *
 */

import fs from 'node:fs/promises'
import path from 'node:path'
import { setupMcpServers } from '../commands/setup/mcp'
import { indexProject as indexBm25, updateProjectIndex as updateBm25 } from '../domain/bm25'
import { indexCoChanges } from '../domain/git-cochange'
import { indexImports, updateImportGraph } from '../domain/import-graph'
import { getErrorMessage } from '../errors'
import { detectCodex, getActiveProvider } from '../infrastructure/ai-provider'
import { verifyCodexPRouterReady } from '../infrastructure/codex-skill'
import commandInstaller from '../infrastructure/command-installer'
import configManager from '../infrastructure/config-manager'
import pathManager from '../infrastructure/path-manager'
import { analysisStorage } from '../storage/analysis-storage'
import { ideasStorage } from '../storage/ideas-storage'
import llmAnalysisStorage from '../storage/llm-analysis-storage'
import { migrateJsonToSqlite, sweepLegacyJson } from '../storage/migrate-json'
import { queueStorage } from '../storage/queue-storage'
import { shippedStorage } from '../storage/shipped-storage'
import { stateStorage } from '../storage/state-storage'
import { velocityStorage } from '../storage/velocity-storage'
import type { ProjectSyncResult, SyncOptions } from '../types/project-sync'
import type { Context7Status } from '../types/services.js'
import type { VerificationReport } from '../types/sync-verifier'
import { readJson } from '../utils/file-helper'
import log from '../utils/logger'
import { repairContextQuality } from './context-quality-service'
import context7Service from './context7-service'
import { writeProjectAgentSurfaces } from './project-agent-surfaces'
import { skillGenerator } from './skill-generator'
import { emptyCommands, emptyGitData, emptyStack, emptyStats } from './sync/defaults'
import { detectIncrementalChanges } from './sync/incremental'
import { archiveStaleData, recordSyncMetrics, saveDraftAnalysis } from './sync/persistence'
import { runSyncPhase as phase, withPhaseTimeout as withTimeout } from './sync/phase-runner'
import {
  ensureProjectDirectories,
  logSyncEvent,
  updateProjectDoc,
  updateStateDoc,
} from './sync/state-update'
import { analyzeGit, detectCommands, detectStack, gatherStats } from './sync-analyzer'
import { syncVerifier } from './sync-verifier'
import { publishWorkCostSnapshots } from './work-cost-service'

// SYNC SERVICE

class SyncService {
  private projectPath: string
  private projectId: string | null = null
  private globalPath: string = ''
  private cliVersion: string = '0.0.0'

  constructor() {
    this.projectPath = process.cwd()
  }

  /**
   * Main sync method - does everything in one call
   */
  async sync(
    projectPath: string = process.cwd(),
    options: SyncOptions = {}
  ): Promise<ProjectSyncResult> {
    this.projectPath = projectPath
    const startTime = Date.now()

    let context7Status: Context7Status = {
      installed: false,
      verified: false,
      configPath: '',
      message: '',
    }

    try {
      // 1. Get project config
      this.projectId = await configManager.getProjectId(projectPath)
      if (!this.projectId) {
        return {
          success: false,
          projectId: '',
          cliVersion: '',
          git: emptyGitData(),
          stats: emptyStats(),
          commands: emptyCommands(),
          stack: emptyStack(),
          context7: { installed: false, verified: false },
          error: 'No prjct project. Run p. init first.',
        }
      }

      this.globalPath = pathManager.getGlobalProjectPath(this.projectId)
      this.cliVersion = await this.getCliVersion()

      // Cleanup legacy agent files generated by prjct (replaced by skills)
      await fs
        .rm(path.join(this.globalPath, 'agents'), { recursive: true, force: true })
        .catch(() => {})

      // Codex router check — non-blocking, sync should succeed for other providers
      const codexDetection = await detectCodex()
      if (codexDetection.installed) {
        const codexRouter = await verifyCodexPRouterReady({ autoRepair: true })
        if (!codexRouter.verified) {
          log.warn(`Codex p. router not ready: ${codexRouter.message || 'verification failed'}`)
        }
      }

      // Keep prjct-managed MCP defaults self-healing from sync as well as setup.
      await phase('mcp-defaults', () => setupMcpServers({ silent: true, verifyContext7: false }))

      // Context7 is best-effort, never a hard gate, and provider-aware: it
      // configures into the ACTIVE harness's MCP config (Claude → mcp.json,
      // Codex → config.toml). Its smoke check needs network, so a hard failure
      // here used to abort sync entirely for Codex/Gemini and any sandboxed/
      // offline run — even though indexing, memory and vault regen don't depend
      // on it. Mirror the Codex-router check above: try, warn on failure, keep
      // going. `verified:false` still surfaces so `prjct start`/setup can repair.
      const activeProvider = await getActiveProvider().catch(() => null)
      const context7Provider = activeProvider?.name ?? 'claude'
      try {
        context7Status = await phase('context7', () =>
          context7Service.ensureReady(context7Provider)
        )
      } catch (error) {
        const message = getErrorMessage(error)
        log.warn(`Context7 MCP not ready (continuing sync): ${message}`)
        context7Status = {
          installed: context7Status.installed,
          verified: false,
          configPath: context7Status.configPath,
          message,
        }
      }

      // 2. Ensure directories exist (non-blocking)
      const ensureDirsPromise = ensureProjectDirectories(this.globalPath)

      // 2b. Auto-migrate JSON → SQLite (idempotent, skips if already done).
      // Deprecation track: the JSON layout shipped pre-v1.24.1; every v2.x
      // install has long since migrated. Set PRJCT_SKIP_JSON_MIGRATION=1 to
      // skip this and the sweep below. v3.0 will remove migrate-json.ts.
      await ensureDirsPromise
      const skipJsonMigration = process.env.PRJCT_SKIP_JSON_MIGRATION === '1'
      if (!skipJsonMigration) {
        await phase('migrate', () => migrateJsonToSqlite(this.projectId!))

        // 2c. Sweep leftover JSON files → import to SQLite → delete
        // Runs every sync to catch ghosts from old code or failed migrations
        await phase('sweep', async () => {
          try {
            const swept = await sweepLegacyJson(this.projectId!)
            if (swept > 0) {
              log.info('Swept legacy JSON files into SQLite', { swept })
            }
          } catch (error) {
            log.debug('Legacy JSON sweep failed (non-critical)', {
              error: getErrorMessage(error),
            })
          }
        })
      }

      // 2d. Legacy crew-disk sweep (spec a50b32d1 AC #10) — detect
      // pre-v2.19.7 `.prjct/CHECKPOINTS.md` and `.prjct/team.json`,
      // migrate into kv_store, emit one-shot inbox warnings on
      // post-migration hand-edits. mtime-cached so re-syncs are silent.
      //
      // Deprecation track: pre-v2.19.7 was ~12 months ago — every active
      // install migrated long ago. Set PRJCT_SKIP_CREW_SWEEP=1 to skip this
      // phase entirely (mirrors PRJCT_SKIP_JSON_MIGRATION). v3.0 removes
      // the sweep file along with migrate-json.
      if (process.env.PRJCT_SKIP_CREW_SWEEP !== '1') {
        await phase('legacy-crew-sweep', async () => {
          try {
            const { legacyCrewSweep } = await import('./legacy-crew-sweep')
            const result = await legacyCrewSweep(this.projectPath, this.projectId!)
            if (
              result.checkpointsMigrated ||
              result.teamMigrated ||
              result.checkpointsHandEditWarned ||
              result.teamHandEditWarned ||
              result.errors.length > 0
            ) {
              log.info('Legacy crew sweep ran', {
                checkpointsMigrated: result.checkpointsMigrated,
                teamMigrated: result.teamMigrated,
                checkpointsHandEditWarned: result.checkpointsHandEditWarned,
                teamHandEditWarned: result.teamHandEditWarned,
                errors: result.errors.length,
              })
            }
          } catch (error) {
            log.debug('Legacy crew sweep failed (non-critical)', {
              error: getErrorMessage(error),
            })
          }
        })
      }

      // 3. Gather all data IN PARALLEL (30-50% speedup)
      // These operations are independent and can run concurrently
      const [git, stats, commands, stack] = await phase('gather', () =>
        withTimeout(
          Promise.all([
            analyzeGit(this.projectPath),
            gatherStats(this.projectPath),
            detectCommands(this.projectPath),
            detectStack(this.projectPath),
          ]),
          'gather'
        )
      )

      // 3a. Incremental change detection — see ./sync/incremental.ts for the
      // hash-based diff + import-graph propagation.
      const {
        shouldRebuildIndexes,
        changedDomains: _changedDomains,
        incrementalInfo,
        changedSourceFiles,
        deletedSourceFiles,
      } = await phase('incremental', () =>
        detectIncrementalChanges({
          projectId: this.projectId!,
          projectPath: this.projectPath,
          isFullSync: options.full === true,
          changedFilesHint: options.changedFiles,
        })
      )

      // 3b. Build file-ranking indexes IN PARALLEL (BM25, import graph, co-change)
      // Skip if no source files changed (incremental optimization)
      if (shouldRebuildIndexes) {
        await phase('index', async () => {
          try {
            const canUseIncrementalIndexes =
              incrementalInfo?.isIncremental &&
              (changedSourceFiles.length > 0 || deletedSourceFiles.length > 0)
            await Promise.all([
              canUseIncrementalIndexes
                ? updateBm25(
                    this.projectPath,
                    this.projectId!,
                    changedSourceFiles,
                    deletedSourceFiles
                  )
                : indexBm25(this.projectPath, this.projectId!),
              canUseIncrementalIndexes
                ? updateImportGraph(
                    this.projectPath,
                    this.projectId!,
                    changedSourceFiles,
                    deletedSourceFiles
                  )
                : indexImports(this.projectPath, this.projectId!),
              indexCoChanges(this.projectPath, this.projectId!),
            ])
          } catch (error) {
            log.debug('File ranking index build failed (non-critical)', {
              error: getErrorMessage(error),
            })
          }
        })
      }

      // 4. Generate native workflow skills (installed to ~/.claude/skills/)
      // Collect rich context from SQLite for context-rich skills
      let generatedSkills: import('../types/project-sync').ProjectSyncResult['generatedSkills']
      const skillPhaseStart = Date.now()
      log.debug('sync phase start', { phase: 'skills' })
      try {
        const [
          llmAnalysis,
          activeAnalysisForSkills,
          recentShippedFeatures,
          velocityData,
          backlog,
          taskHistory,
          allPausedTasks,
          feedbackForSkills,
          currentTask,
          ideaCounts,
          shippedCount,
        ] = await Promise.all([
          Promise.resolve(llmAnalysisStorage.getActive(this.projectId!)).catch(() => null),
          analysisStorage.getActive(this.projectId!).catch(() => null),
          shippedStorage.getRecent(this.projectId!, 3).catch(() => []),
          velocityStorage.getMetrics(this.projectId!).catch(() => null),
          queueStorage.getBacklog(this.projectId!).catch(() => []),
          stateStorage.getTaskHistory(this.projectId!).catch(() => []),
          stateStorage.getAllPausedTasks(this.projectId!).catch(() => []),
          stateStorage.getAggregatedFeedback(this.projectId!).catch(() => null),
          stateStorage.getCurrentTask(this.projectId!).catch(() => null),
          ideasStorage
            .getCounts(this.projectId!)
            .catch(() => ({ pending: 0, converted: 0, archived: 0 })),
          shippedStorage.getCount(this.projectId!).catch(() => 0),
        ])

        const conditionCtx = {
          backlogCount: backlog.length,
          completedTaskCount: taskHistory.length,
          pausedTaskCount: allPausedTasks.length,
          hasActiveTask: !!currentTask,
        }

        // Prefer LLM analysis patterns (accurate), fallback to heuristic
        // Filter out source='repo' patterns — those were heuristic regex detections (next/image, UiButton, etc.)
        // that are unreliable. Real patterns come from LLM analysis or baseline/feedback.
        const patterns = llmAnalysis
          ? llmAnalysis.patterns.map((p) => ({
              name: p.name,
              description: p.description,
              location: p.locations?.[0],
            }))
          : (activeAnalysisForSkills?.patterns ?? [])
              .filter((p: Record<string, unknown>) => p.source !== 'repo')
              .map((p) => ({
                name: p.name,
                description: p.description,
                location: p.location,
              }))

        const antiPatterns = llmAnalysis
          ? llmAnalysis.antiPatterns.map((a) => ({
              issue: a.issue,
              file: a.files?.[0] ?? 'multiple',
              suggestion: a.suggestion,
              severity: a.severity ?? 'medium',
            }))
          : (activeAnalysisForSkills?.antiPatterns ?? [])
              .filter((a: Record<string, unknown>) => a.source !== 'repo')
              .map((a) => ({
                issue: a.issue,
                file: a.file,
                suggestion: a.suggestion,
                severity: a.severity ?? 'medium',
              }))

        // Commands: LLM analysis > heuristic detectCommands
        const resolvedCommands = llmAnalysis?.commands
          ? {
              install: llmAnalysis.commands.install ?? commands.install,
              run: commands.run,
              test: llmAnalysis.commands.test ?? commands.test,
              build: llmAnalysis.commands.build ?? commands.build,
              dev: llmAnalysis.commands.dev ?? commands.dev,
              lint: llmAnalysis.commands.lint ?? commands.lint,
              format: llmAnalysis.commands.format ?? commands.format,
            }
          : commands

        // Build rich context for skill bodies
        const richContext = {
          version: stats.version,
          fileCount: stats.fileCount,
          patterns,
          antiPatterns,
          recentShipped: recentShippedFeatures.map((s) => ({
            name: s.name,
            type: s.type ?? 'feature',
            duration: s.duration,
            filesChanged: s.changes?.length,
          })),
          velocity: velocityData
            ? {
                avgPoints: velocityData.averageVelocity,
                trend: velocityData.velocityTrend,
                accuracy: velocityData.estimationAccuracy,
              }
            : null,
          backlogCount: backlog.length,
          knownGotchas: feedbackForSkills?.knownGotchas ?? [],
          userPatterns: feedbackForSkills?.patternsDiscovered ?? [],

          // Task state for rich skills — counts only; descriptions
          // deliberately never enter the skill body (formatState).
          pausedTasks: allPausedTasks.map((t) => ({
            description: t.description,
            pausedAt: ((t as Record<string, unknown>).pausedAt as string) ?? '',
          })),
          ideasCount: ideaCounts?.pending ?? 0,
          shippedCount: shippedCount,
        }

        generatedSkills = await skillGenerator.generateAndInstall(
          {
            success: true,
            projectId: this.projectId!,
            cliVersion: this.cliVersion,
            git,
            stats,
            commands: resolvedCommands,
            stack,
          },
          conditionCtx,
          richContext
        )
      } catch (error) {
        log.debug('Native skill generation failed (non-critical)', {
          error: getErrorMessage(error),
        })
      }
      log.debug('sync phase done', { phase: 'skills', ms: Date.now() - skillPhaseStart })

      // 5. Update files IN PARALLEL (write to different files)
      await phase('update-files', () =>
        Promise.all([
          updateProjectDoc({
            projectId: this.projectId!,
            projectPath: this.projectPath,
            cliVersion: this.cliVersion,
            git,
            stats,
          }),
          updateStateDoc({
            projectId: this.projectId!,
            projectPath: this.projectPath,
            stats,
            stack,
          }),
          Promise.resolve(logSyncEvent(this.projectId!, git, stats)),
          saveDraftAnalysis(
            this.projectId!,
            this.projectPath,
            git,
            stats,
            stack,
            context7Status.verified
          ),
        ])
      )

      const activeAnalysis = await analysisStorage.getActive(this.projectId)
      const analysisSummary = {
        patterns: activeAnalysis?.patterns?.length || 0,
        antiPatterns: activeAnalysis?.antiPatterns?.length || 0,
        criticalAntiPatterns:
          activeAnalysis?.antiPatterns?.filter((a) => a.severity === 'high').length || 0,
      }

      // 9. Record metrics for value dashboard
      const duration = Date.now() - startTime
      const syncMetrics = await phase('metrics', () =>
        recordSyncMetrics(this.projectId!, stats, duration)
      )
      const workCost = await phase('work-cost', () => publishWorkCostSnapshots(this.projectId!))

      // 9b. Archive stale data (PRJ-267)
      await phase('archive', () => archiveStaleData(this.projectId!))

      // 9c. Context quality cleanup — repair historical generated junk from
      // older versions so sync leaves the second-brain read model usable.
      const contextQuality = await phase('context-quality', () =>
        repairContextQuality(this.projectPath, this.projectId!)
      )

      // 10. Update global config and commands (CLI does EVERYTHING)
      // This ensures `prjct sync` from terminal updates global CLAUDE.md and commands
      await phase('install-global', async () => {
        await commandInstaller.installGlobalConfig()
        await commandInstaller.syncCommands()
      })

      await phase('install-agent-surfaces', async () => {
        await writeProjectAgentSurfaces(this.projectPath)
      })

      // 11. Run verification checks (built-in + custom from config)
      let verification: VerificationReport | undefined
      await phase('verify', async () => {
        try {
          const localConfig = await configManager.readConfig(this.projectPath)
          verification = await syncVerifier.verify(
            this.projectPath,
            this.globalPath,
            localConfig?.verification
          )
        } catch (error) {
          log.debug('Verification failed (non-critical)', { error: getErrorMessage(error) })
        }
      })

      return {
        success: true,
        projectId: this.projectId,
        cliVersion: this.cliVersion,
        git,
        stats,
        commands,
        stack,
        context7: {
          installed: context7Status.installed,
          verified: context7Status.verified,
          message: context7Status.message,
        },
        analysisSummary,
        contextQuality,
        syncMetrics,
        workCost,
        verification,
        incremental: incrementalInfo,
        generatedSkills,
      }
    } catch (error) {
      return {
        success: false,
        projectId: this.projectId || '',
        cliVersion: this.cliVersion,
        git: emptyGitData(),
        stats: emptyStats(),
        commands: emptyCommands(),
        stack: emptyStack(),
        context7: {
          installed: context7Status.installed,
          verified: context7Status.verified,
          message: context7Status.message,
        },
        error: getErrorMessage(error),
      }
    }
  }

  // DIRECTORY SETUP

  // PROJECT.JSON UPDATE

  // STATE.JSON UPDATE

  // MEMORY LOGGING

  // METRICS RECORDING

  /**
   * Record sync metrics for the value dashboard
   *
   * Uses REAL token counts from the BM25 index (actual project tokens)
   * instead of estimates. filteredSize = agent context files that get
   * loaded into the AI conversation.
   */
  // DRAFT ANALYSIS (PRJ-263)

  /**
   * Save sync results as a draft analysis.
   * Preserves existing sealed analysis — only the draft is overwritten.
   * Incorporates task feedback from completed tasks (PRJ-272).
   */
  // ARCHIVAL (PRJ-267)

  private async getCliVersion(): Promise<string> {
    try {
      const pkgPath = path.join(__dirname, '..', '..', 'package.json')
      const pkg = await readJson<{ version?: string }>(pkgPath)
      return pkg?.version || '0.0.0'
    } catch (error) {
      log.debug('Failed to read CLI version', { error: getErrorMessage(error) })
      return '0.0.0'
    }
  }
}

export const syncService = new SyncService()
export { SyncService }
