/**
 * SyncService - Comprehensive Project Sync
 *
 * Handles ALL sync operations in a single TypeScript execution:
 * - Git analysis
 * - Project stats
 * - Native skill generation
 * - State updates
 *
 * This eliminates the need for Claude to make 50+ individual tool calls.
 * Instead, one command does everything.
 *
 * Analysis/stats functions extracted to ./sync-analyzer.ts
 *
 * @version 2.0.0
 */

import fs from 'node:fs/promises'
import path from 'node:path'
import { SemanticMemories } from '../agentic/semantic-memories'
import { indexProject as indexBm25, loadIndex as loadBm25Index } from '../domain/bm25'
import { affectedDomains, propagateChanges } from '../domain/change-propagator'
import { detectChanges, hasHashRegistry, saveHashes } from '../domain/file-hasher'
import { indexCoChanges, loadMatrix as loadCoChangeMatrix } from '../domain/git-cochange'
import { indexImports, loadGraph as loadImportGraph } from '../domain/import-graph'
import { getErrorMessage } from '../errors'
import { detectCodex } from '../infrastructure/ai-provider'
import commandInstaller from '../infrastructure/command-installer'
import configManager from '../infrastructure/config-manager'
import pathManager from '../infrastructure/path-manager'
import { verifyCodexPRouterReady } from '../infrastructure/setup'
import { analysisStorage } from '../storage/analysis-storage'
import { archiveStorage } from '../storage/archive-storage'
import { prjctDb } from '../storage/database'
import { ideasStorage } from '../storage/ideas-storage'
import llmAnalysisStorage from '../storage/llm-analysis-storage'
import { metricsStorage } from '../storage/metrics-storage'
import { migrateJsonToSqlite, sweepLegacyJson } from '../storage/migrate-json'
import { queueStorage } from '../storage/queue-storage'
import { shippedStorage } from '../storage/shipped-storage'
import { stateStorage } from '../storage/state-storage'
import { velocityStorage } from '../storage/velocity-storage'
import type {
  GitData,
  IncrementalInfo,
  ProjectCommands,
  ProjectStats,
  ProjectSyncResult,
  SyncMetrics,
  SyncOptions,
} from '../types/project-sync'
import type { Context7Status } from '../types/services.js'
import type { StackDetection } from '../types/stack'
import type { VerificationReport } from '../types/sync-verifier'
import * as dateHelper from '../utils/date-helper'
import { readJson } from '../utils/file-helper'
import log from '../utils/logger'
import { outcomeMemoryLearner } from '../workflows/outcome-learner'
import { outcomeStorage } from '../workflows/outcome-storage'
import context7Service from './context7-service'
import { localStateGenerator } from './local-state-generator'
import { memoryService } from './memory-service'
import patternExtractor from './pattern-extractor'
import { skillGenerator } from './skill-generator'
import { analyzeGit, detectCommands, detectStack, gatherStats } from './sync-analyzer'
import { syncVerifier } from './sync-verifier'

// ============================================================================
// SYNC SERVICE
// ============================================================================

class SyncService {
  private projectPath: string
  private projectId: string | null = null
  private globalPath: string = ''
  private cliVersion: string = '0.0.0'

  constructor() {
    this.projectPath = process.cwd()
  }

  /**
   * Main sync method - does everything in one call
   */
  async sync(
    projectPath: string = process.cwd(),
    options: SyncOptions = {}
  ): Promise<ProjectSyncResult> {
    this.projectPath = projectPath
    const startTime = Date.now()

    let context7Status: Context7Status = {
      installed: false,
      verified: false,
      configPath: '',
      message: '',
    }

    try {
      // 1. Get project config
      this.projectId = await configManager.getProjectId(projectPath)
      if (!this.projectId) {
        return {
          success: false,
          projectId: '',
          cliVersion: '',
          git: this.emptyGitData(),
          stats: this.emptyStats(),
          commands: this.emptyCommands(),
          stack: this.emptyStack(),
          context7: { installed: false, verified: false },
          error: 'No prjct project. Run p. init first.',
        }
      }

      this.globalPath = pathManager.getGlobalProjectPath(this.projectId)
      this.cliVersion = await this.getCliVersion()

      // Cleanup legacy agent files generated by prjct (replaced by skills)
      await fs
        .rm(path.join(this.globalPath, 'agents'), { recursive: true, force: true })
        .catch(() => {})

      // Codex router check — non-blocking, sync should succeed for other providers
      const codexDetection = await detectCodex()
      if (codexDetection.installed) {
        const codexRouter = await verifyCodexPRouterReady({ autoRepair: true })
        if (!codexRouter.verified) {
          log.warn(`Codex p. router not ready: ${codexRouter.message || 'verification failed'}`)
        }
      }

      // Context7 is mandatory for deterministic coding workflows
      try {
        context7Status = await context7Service.ensureReady()
      } catch (error) {
        return {
          success: false,
          projectId: this.projectId,
          cliVersion: this.cliVersion,
          git: this.emptyGitData(),
          stats: this.emptyStats(),
          commands: this.emptyCommands(),
          stack: this.emptyStack(),
          context7: {
            installed: context7Status.installed,
            verified: false,
            message: getErrorMessage(error),
          },
          error: `Context7 MCP is required but not ready: ${getErrorMessage(error)}. Run 'prjct start' to repair.`,
        }
      }

      // 2. Ensure directories exist (non-blocking)
      const ensureDirsPromise = this.ensureDirectories()

      // 2b. Auto-migrate JSON → SQLite (idempotent, skips if already done)
      await ensureDirsPromise
      await migrateJsonToSqlite(this.projectId)

      // 2c. Sweep leftover JSON files → import to SQLite → delete
      // Runs every sync to catch ghosts from old code or failed migrations
      try {
        const swept = await sweepLegacyJson(this.projectId)
        if (swept > 0) {
          log.info('Swept legacy JSON files into SQLite', { swept })
        }
      } catch (error) {
        log.debug('Legacy JSON sweep failed (non-critical)', { error: getErrorMessage(error) })
      }

      // 3. Gather all data IN PARALLEL (30-50% speedup)
      // These operations are independent and can run concurrently
      const [git, stats, commands, stack] = await Promise.all([
        analyzeGit(this.projectPath),
        gatherStats(this.projectPath),
        detectCommands(this.projectPath),
        detectStack(this.projectPath),
      ])

      // 3a. Incremental change detection
      // Determine if we can skip expensive operations based on file changes
      const isFullSync = options.full === true
      let incrementalInfo: IncrementalInfo | undefined
      let shouldRebuildIndexes = true
      let changedDomains = new Set<string>()

      if (!isFullSync && hasHashRegistry(this.projectId!)) {
        try {
          const { diff, currentHashes } = await detectChanges(this.projectPath, this.projectId!)
          const totalChanged = diff.added.length + diff.modified.length + diff.deleted.length

          if (totalChanged === 0 && !options.changedFiles?.length) {
            // Nothing changed — skip expensive rebuilds
            shouldRebuildIndexes = false
            incrementalInfo = {
              isIncremental: true,
              filesChanged: 0,
              filesUnchanged: diff.unchanged.length,
              indexesRebuilt: false,
              affectedDomains: [],
            }
          } else {
            // Some files changed — propagate through import graph
            const propagated = propagateChanges(diff, this.projectId!)
            changedDomains = affectedDomains(propagated.allAffected)

            // Only rebuild indexes if source files changed
            const sourceExtensions = new Set(['.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs'])
            const hasSourceChanges = propagated.allAffected.some((f) => {
              const ext = f.substring(f.lastIndexOf('.'))
              return sourceExtensions.has(ext)
            })
            shouldRebuildIndexes = hasSourceChanges

            incrementalInfo = {
              isIncremental: true,
              filesChanged: totalChanged,
              filesUnchanged: diff.unchanged.length,
              indexesRebuilt: shouldRebuildIndexes,
              affectedDomains: Array.from(changedDomains),
            }
          }

          // Save updated hashes AFTER determining diff (commit new state)
          saveHashes(this.projectId!, currentHashes)
        } catch (error) {
          log.debug('Incremental detection failed, falling back to full sync', {
            error: getErrorMessage(error),
          })
          // Fall through to full sync
        }
      } else {
        // First sync or --full flag: compute and save hashes for next time
        try {
          const { currentHashes } = await detectChanges(this.projectPath, this.projectId!)
          saveHashes(this.projectId!, currentHashes)
        } catch (error) {
          log.debug('Hash computation failed (non-critical)', {
            error: getErrorMessage(error),
          })
        }
      }

      // 3b. Build file-ranking indexes IN PARALLEL (BM25, import graph, co-change)
      // Skip if no source files changed (incremental optimization)
      if (shouldRebuildIndexes) {
        try {
          await Promise.all([
            indexBm25(this.projectPath, this.projectId!),
            indexImports(this.projectPath, this.projectId!),
            indexCoChanges(this.projectPath, this.projectId!),
          ])
        } catch (error) {
          log.debug('File ranking index build failed (non-critical)', {
            error: getErrorMessage(error),
          })
        }
      }

      // 4. Generate native workflow skills (installed to ~/.claude/skills/)
      // Collect rich context from SQLite for context-rich skills
      let generatedSkills: import('../types/project-sync').ProjectSyncResult['generatedSkills']
      try {
        const [
          llmAnalysis,
          activeAnalysisForSkills,
          recentShippedFeatures,
          velocityData,
          backlog,
          taskHistory,
          allPausedTasks,
          feedbackForSkills,
          currentTask,
          ideaCounts,
          shippedCount,
        ] = await Promise.all([
          Promise.resolve(llmAnalysisStorage.getActive(this.projectId!)).catch(() => null),
          analysisStorage.getActive(this.projectId!).catch(() => null),
          shippedStorage.getRecent(this.projectId!, 3).catch(() => []),
          velocityStorage.getMetrics(this.projectId!).catch(() => null),
          queueStorage.getBacklog(this.projectId!).catch(() => []),
          stateStorage.getTaskHistory(this.projectId!).catch(() => []),
          stateStorage.getAllPausedTasks(this.projectId!).catch(() => []),
          stateStorage.getAggregatedFeedback(this.projectId!).catch(() => null),
          stateStorage.getCurrentTask(this.projectId!).catch(() => null),
          ideasStorage
            .getCounts(this.projectId!)
            .catch(() => ({ pending: 0, converted: 0, archived: 0 })),
          shippedStorage.getCount(this.projectId!).catch(() => 0),
        ])

        const conditionCtx = {
          backlogCount: backlog.length,
          completedTaskCount: taskHistory.length,
          pausedTaskCount: allPausedTasks.length,
          hasActiveTask: !!currentTask,
        }

        // Prefer LLM analysis patterns (accurate), fallback to heuristic
        // Filter out source='repo' patterns — those were heuristic regex detections (next/image, UiButton, etc.)
        // that are unreliable. Real patterns come from LLM analysis or baseline/feedback.
        const patterns = llmAnalysis
          ? llmAnalysis.patterns.map((p) => ({
              name: p.name,
              description: p.description,
              location: p.locations?.[0],
            }))
          : (activeAnalysisForSkills?.patterns ?? [])
              .filter((p: Record<string, unknown>) => p.source !== 'repo')
              .map((p) => ({
                name: p.name,
                description: p.description,
                location: p.location,
              }))

        const antiPatterns = llmAnalysis
          ? llmAnalysis.antiPatterns.map((a) => ({
              issue: a.issue,
              file: a.files?.[0] ?? 'multiple',
              suggestion: a.suggestion,
              severity: a.severity ?? 'medium',
            }))
          : (activeAnalysisForSkills?.antiPatterns ?? [])
              .filter((a: Record<string, unknown>) => a.source !== 'repo')
              .map((a) => ({
                issue: a.issue,
                file: a.file,
                suggestion: a.suggestion,
                severity: a.severity ?? 'medium',
              }))

        // Commands: LLM analysis > heuristic detectCommands
        const resolvedCommands = llmAnalysis?.commands
          ? {
              install: llmAnalysis.commands.install ?? commands.install,
              run: commands.run,
              test: llmAnalysis.commands.test ?? commands.test,
              build: llmAnalysis.commands.build ?? commands.build,
              dev: llmAnalysis.commands.dev ?? commands.dev,
              lint: llmAnalysis.commands.lint ?? commands.lint,
              format: llmAnalysis.commands.format ?? commands.format,
            }
          : commands

        // Build rich context for skill bodies
        const richContext = {
          version: stats.version,
          fileCount: stats.fileCount,
          patterns,
          antiPatterns,
          recentShipped: recentShippedFeatures.map((s) => ({
            name: s.name,
            type: s.type ?? 'feature',
            duration: s.duration,
            filesChanged: s.changes?.length,
          })),
          velocity: velocityData
            ? {
                avgPoints: velocityData.averageVelocity,
                trend: velocityData.velocityTrend,
                accuracy: velocityData.estimationAccuracy,
              }
            : null,
          backlogCount: backlog.length,
          completedTaskCount: taskHistory.length,
          pausedTaskCount: allPausedTasks.length,
          knownGotchas: feedbackForSkills?.knownGotchas ?? [],
          userPatterns: feedbackForSkills?.patternsDiscovered ?? [],

          // Task state for rich skills
          hasActiveTask: !!currentTask,
          activeTaskDescription: currentTask?.description ?? '',
          pausedTasks: allPausedTasks.map((t) => ({
            description: t.description,
            pausedAt: ((t as Record<string, unknown>).pausedAt as string) ?? '',
          })),
          topBacklog: backlog.slice(0, 3).map((t) => ({
            description: t.description,
            priority: ((t as Record<string, unknown>).priority as string) ?? 'medium',
          })),
          ideasCount: ideaCounts?.pending ?? 0,
          shippedCount: shippedCount,
        }

        generatedSkills = await skillGenerator.generateAndInstall(
          {
            success: true,
            projectId: this.projectId!,
            cliVersion: this.cliVersion,
            git,
            stats,
            commands: resolvedCommands,
            stack,
          },
          conditionCtx,
          richContext
        )
      } catch (error) {
        log.debug('Native skill generation failed (non-critical)', {
          error: getErrorMessage(error),
        })
      }

      // 5. Update files IN PARALLEL (write to different files)
      await Promise.all([
        this.updateProjectJson(git, stats),
        this.updateStateJson(stats, stack),
        this.logToMemory(git, stats),
        this.saveDraftAnalysis(git, stats, stack, context7Status.verified),
      ])

      const activeAnalysis = await analysisStorage.getActive(this.projectId)
      const analysisSummary = {
        patterns: activeAnalysis?.patterns?.length || 0,
        antiPatterns: activeAnalysis?.antiPatterns?.length || 0,
        criticalAntiPatterns:
          activeAnalysis?.antiPatterns?.filter((a) => a.severity === 'high').length || 0,
      }

      // 9. Record metrics for value dashboard
      const duration = Date.now() - startTime
      const syncMetrics = await this.recordSyncMetrics(stats, duration)

      // 9b. Archive stale data (PRJ-267)
      await this.archiveStaleData()

      // 9c. Auto-learn from task history → memory (PRJ-283)
      await this.autoLearnFromHistory()

      // 10. Update global config and commands (CLI does EVERYTHING)
      // This ensures `prjct sync` from terminal updates global CLAUDE.md and commands
      await commandInstaller.installGlobalConfig()
      await commandInstaller.syncCommands()

      // 11. Run verification checks (built-in + custom from config)
      let verification: VerificationReport | undefined
      try {
        const localConfig = await configManager.readConfig(this.projectPath)
        verification = await syncVerifier.verify(
          this.projectPath,
          this.globalPath,
          localConfig?.verification
        )
      } catch (error) {
        log.debug('Verification failed (non-critical)', { error: getErrorMessage(error) })
      }

      return {
        success: true,
        projectId: this.projectId,
        cliVersion: this.cliVersion,
        git,
        stats,
        commands,
        stack,
        context7: {
          installed: context7Status.installed,
          verified: context7Status.verified,
          message: context7Status.message,
        },
        analysisSummary,
        syncMetrics,
        verification,
        incremental: incrementalInfo,
        generatedSkills,
      }
    } catch (error) {
      return {
        success: false,
        projectId: this.projectId || '',
        cliVersion: this.cliVersion,
        git: this.emptyGitData(),
        stats: this.emptyStats(),
        commands: this.emptyCommands(),
        stack: this.emptyStack(),
        context7: {
          installed: context7Status.installed,
          verified: context7Status.verified,
          message: context7Status.message,
        },
        error: getErrorMessage(error),
      }
    }
  }

  // ==========================================================================
  // DIRECTORY SETUP
  // ==========================================================================

  private async ensureDirectories(): Promise<void> {
    const dirs = ['storage', 'context', 'memory', 'analysis', 'config', 'sync']
    // Create all directories IN PARALLEL
    await Promise.all(
      dirs.map((dir) => fs.mkdir(path.join(this.globalPath, dir), { recursive: true }))
    )
  }

  // ==========================================================================
  // PROJECT.JSON UPDATE
  // ==========================================================================

  private async updateProjectJson(git: GitData, stats: ProjectStats): Promise<void> {
    // Read existing from SQLite
    const existing: Record<string, unknown> =
      prjctDb.getDoc<Record<string, unknown>>(this.projectId!, 'project') || {}

    const updated = {
      ...existing,
      projectId: this.projectId,
      repoPath: this.projectPath,
      name: stats.name,
      version: stats.version,
      cliVersion: this.cliVersion,
      techStack: stats.frameworks,
      fileCount: stats.fileCount,
      commitCount: git.commits,
      stack: stats.ecosystem,
      currentBranch: git.branch,
      hasUncommittedChanges: git.hasChanges,
      createdAt: existing.createdAt || dateHelper.getTimestamp(),
      lastSync: dateHelper.getTimestamp(),
      // Staleness tracking (PRJ-120)
      lastSyncCommit: git.recentCommits[0]?.hash || null,
      lastSyncBranch: git.branch,
    }

    prjctDb.setDoc(this.projectId!, 'project', updated)
  }

  // ==========================================================================
  // STATE.JSON UPDATE
  // ==========================================================================

  private async updateStateJson(stats: ProjectStats, stack: StackDetection): Promise<void> {
    // Read existing from SQLite via stateStorage
    const stateData = await stateStorage.read(this.projectId!)
    const state: Record<string, unknown> = { ...stateData }

    // Update with enterprise fields
    state.projectId = this.projectId
    state.stack = {
      language: stats.languages[0] || 'Unknown',
      framework: stats.frameworks[0] || null,
    }
    state.domains = {
      hasFrontend: stack.hasFrontend,
      hasBackend: stack.hasBackend,
      hasDatabase: stack.hasDatabase,
      hasTesting: stack.hasTesting,
      hasDocker: stack.hasDocker,
    }
    state.projectType = stats.projectType
    state.metrics = {
      totalFiles: stats.fileCount,
    }
    state.lastSync = dateHelper.getTimestamp()
    state.lastUpdated = dateHelper.getTimestamp()
    state.context = {
      ...((state.context as Record<string, unknown>) || {}),
      lastSession: dateHelper.getTimestamp(),
      lastAction: 'Synced project',
      nextAction: 'Run `p. task "description"` to start working',
    }

    await stateStorage.write(this.projectId!, state as import('../schemas/state').StateJson)

    // Also generate local .prjct-state.md (PRJ-112)
    try {
      await localStateGenerator.generate(
        this.projectPath,
        state as import('../schemas/state').StateJson
      )
    } catch (error) {
      log.debug('Local state generation failed (optional)', { error: getErrorMessage(error) })
    }
  }

  // ==========================================================================
  // MEMORY LOGGING
  // ==========================================================================

  private async logToMemory(git: GitData, stats: ProjectStats): Promise<void> {
    prjctDb.appendEvent(this.projectId!, 'sync', {
      branch: git.branch,
      uncommitted: git.hasChanges,
      fileCount: stats.fileCount,
      commitCount: git.commits,
    })
  }

  // ==========================================================================
  // METRICS RECORDING
  // ==========================================================================

  /**
   * Record sync metrics for the value dashboard
   *
   * Uses REAL token counts from the BM25 index (actual project tokens)
   * instead of estimates. filteredSize = agent context files that get
   * loaded into the AI conversation.
   */
  private async recordSyncMetrics(stats: ProjectStats, duration: number): Promise<SyncMetrics> {
    // Real original size from BM25 index (actual tokens indexed from source files)
    let originalSize = 0
    try {
      const bm25 = loadBm25Index(this.projectId!)
      if (bm25) {
        // Sum actual token counts from every indexed file
        for (const doc of Object.values(bm25.documents)) {
          originalSize += doc.length
        }
      }
    } catch (error) {
      log.debug('Could not load BM25 index for metrics', { error: getErrorMessage(error) })
    }

    // Fallback: if no index yet (first sync before indexing), use file count estimate
    if (originalSize === 0) {
      originalSize = stats.fileCount * 200
    }

    // No agent files to measure — skills are loaded natively by Claude Code
    const filteredSize = 0

    const compressionRate =
      originalSize > 0 ? Math.max(0, (originalSize - filteredSize) / originalSize) : 0

    // Record to storage
    try {
      await metricsStorage.recordSync(this.projectId!, {
        originalSize,
        filteredSize,
        duration,
        isWatch: false,
      })
    } catch (error) {
      log.debug('Failed to record sync metrics', { error: getErrorMessage(error) })
    }

    // Collect real index stats
    const indexes: NonNullable<SyncMetrics['indexes']> = {}
    try {
      const bm25 = loadBm25Index(this.projectId!)
      if (bm25) {
        indexes.bm25Files = bm25.totalDocs
        indexes.bm25AvgTokens = Math.round(bm25.avgDocLength)
        indexes.bm25VocabSize = Object.keys(bm25.invertedIndex).length
      }
      const graph = loadImportGraph(this.projectId!)
      if (graph) {
        indexes.importEdges = graph.edgeCount
        indexes.importFiles = graph.fileCount
      }
      const cochange = loadCoChangeMatrix(this.projectId!)
      if (cochange) {
        indexes.cochangeCommits = cochange.commitsAnalyzed
        indexes.cochangeFiles = cochange.filesAnalyzed
      }
    } catch (error) {
      log.debug('Could not load index stats', { error: getErrorMessage(error) })
    }

    return {
      duration,
      originalSize,
      filteredSize,
      compressionRate,
      indexes,
    }
  }

  // ==========================================================================
  // DRAFT ANALYSIS (PRJ-263)
  // ==========================================================================

  /**
   * Save sync results as a draft analysis.
   * Preserves existing sealed analysis — only the draft is overwritten.
   * Incorporates task feedback from completed tasks (PRJ-272).
   */
  private async saveDraftAnalysis(
    git: GitData,
    stats: ProjectStats,
    stack: StackDetection,
    context7Verified: boolean
  ): Promise<void> {
    try {
      const commitHash = git.recentCommits[0]?.hash || null

      // Load aggregated feedback from completed tasks (PRJ-272)
      let patterns: Array<{
        name: string
        description: string
        location?: string
        severity?: 'low' | 'medium' | 'high'
        language?: string
        framework?: string
        source?: 'baseline' | 'repo' | 'context7' | 'feedback'
        confidence?: number
      }> = []
      let antiPatterns: Array<{
        issue: string
        file: string
        suggestion: string
        severity?: 'low' | 'medium' | 'high'
        language?: string
        framework?: string
        source?: 'baseline' | 'repo' | 'context7' | 'feedback'
        confidence?: number
      }> = []
      let feedback:
        | {
            patternsDiscovered: string[]
            knownGotchas: string[]
          }
        | undefined
      try {
        feedback = await stateStorage.getAggregatedFeedback(this.projectId!)

        // Convert discovered patterns to CodePattern objects
        if (feedback.patternsDiscovered.length > 0) {
          patterns = feedback.patternsDiscovered.map((p) => ({
            name: p,
            description: `Discovered during task execution: ${p}`,
            source: 'feedback',
            confidence: 0.74,
          }))
        }

        // Convert known gotchas (recurring issues) to AntiPattern objects
        if (feedback.knownGotchas.length > 0) {
          antiPatterns = feedback.knownGotchas.map((g) => ({
            issue: g,
            file: 'multiple',
            suggestion: `Recurring issue reported across tasks: ${g}`,
            source: 'feedback',
            severity: 'medium',
            confidence: 0.7,
          }))
        }
      } catch {
        // Feedback aggregation failure should not block analysis
      }

      const extracted = await patternExtractor.extract({
        projectId: this.projectId!,
        projectPath: this.projectPath,
        languages: stats.languages,
        frameworks: Array.from(new Set([...stats.frameworks, ...stack.frameworks])),
        feedback,
        context7Verified,
      })

      patterns = extracted.patterns
      antiPatterns = extracted.antiPatterns

      await analysisStorage.saveDraft(this.projectId!, {
        projectId: this.projectId!,
        languages: stats.languages,
        frameworks: stats.frameworks,
        configFiles: [],
        fileCount: stats.fileCount,
        patterns,
        antiPatterns,
        analyzedAt: dateHelper.getTimestamp(),
        status: 'draft',
        commitHash: commitHash ?? undefined,
      })
    } catch (error) {
      log.debug('Failed to save draft analysis (non-critical)', { error: getErrorMessage(error) })
    }
  }

  // ==========================================================================
  // ARCHIVAL (PRJ-267)
  // ==========================================================================

  /**
   * Archive stale data across all storage types.
   * Runs during sync to keep active storage lean.
   */
  private async archiveStaleData(): Promise<void> {
    if (!this.projectId) return

    try {
      const [shipped, dormant, staleQueue, stalePaused, memoryCapped] = await Promise.all([
        shippedStorage.archiveOldShipped(this.projectId).catch(() => 0),
        ideasStorage.markDormantIdeas(this.projectId).catch(() => 0),
        queueStorage.removeStaleCompleted(this.projectId).catch(() => 0),
        stateStorage.archiveStalePausedTasks(this.projectId).catch(() => []),
        memoryService.capEntries(this.projectId).catch(() => 0),
      ])

      const totalArchived =
        shipped + dormant + staleQueue + (stalePaused as unknown[]).length + memoryCapped

      if (totalArchived > 0) {
        log.info('Archived stale data', {
          shipped,
          dormant,
          staleQueue,
          stalePaused: (stalePaused as unknown[]).length,
          memoryCapped,
          total: totalArchived,
        })

        // Record archive stats
        const stats = archiveStorage.getStats(this.projectId)
        log.debug('Archive stats', stats)
      }
    } catch (error) {
      log.debug('Archival failed (non-critical)', { error: getErrorMessage(error) })
    }
  }

  /**
   * Auto-learn from task history and outcomes → inject into memory (PRJ-283).
   * Extracts patterns from completed tasks and injects high-confidence
   * learnings into the semantic memory system.
   */
  private async autoLearnFromHistory(): Promise<void> {
    if (!this.projectId) return

    try {
      const taskHistory = await stateStorage.getTaskHistory(this.projectId)
      if (taskHistory.length === 0) return

      const semanticMemories = new SemanticMemories()
      const result = await outcomeMemoryLearner.learnFromTaskHistory(
        this.projectId,
        taskHistory,
        semanticMemories
      )

      // Also learn from feature outcomes if available
      try {
        const outcomes = await outcomeStorage.getFeatureOutcomes(this.projectId)
        if (outcomes.length > 0) {
          await outcomeMemoryLearner.learnFromOutcomes(this.projectId, outcomes, semanticMemories)
        }
      } catch {
        // Outcome storage may not exist yet
      }

      if (result.memoriesInjected > 0) {
        log.info('Auto-learned from task history', {
          patternsExtracted: result.patternsExtracted,
          memoriesInjected: result.memoriesInjected,
          patternsSkipped: result.patternsSkipped,
        })
      }
    } catch (error) {
      log.debug('Auto-learning failed (non-critical)', { error: getErrorMessage(error) })
    }
  }

  // ==========================================================================
  // HELPERS
  // ==========================================================================

  private async getCliVersion(): Promise<string> {
    try {
      // Try to read from package.json in the module
      const pkgPath = path.join(__dirname, '..', '..', 'package.json')
      const pkg = await readJson<{ version?: string }>(pkgPath)
      return pkg?.version || '0.0.0'
    } catch (error) {
      log.debug('Failed to read CLI version', { error: getErrorMessage(error) })
      return '0.0.0'
    }
  }

  // Empty data structures for error cases
  private emptyGitData(): GitData {
    return {
      branch: 'main',
      commits: 0,
      contributors: 0,
      hasChanges: false,
      stagedFiles: [],
      modifiedFiles: [],
      untrackedFiles: [],
      recentCommits: [],
      weeklyCommits: 0,
    }
  }

  private emptyStats(): ProjectStats {
    return {
      fileCount: 0,
      version: '0.0.0',
      name: 'unknown',
      ecosystem: 'unknown',
      projectType: 'simple',
      languages: [],
      frameworks: [],
    }
  }

  private emptyCommands(): ProjectCommands {
    return {
      install: 'npm install',
      run: 'npm run',
      test: 'npm test',
      build: 'npm run build',
      dev: 'npm run dev',
      lint: 'npm run lint',
      format: 'npm run format',
    }
  }

  private emptyStack(): StackDetection {
    return {
      hasFrontend: false,
      hasBackend: false,
      hasDatabase: false,
      hasDocker: false,
      hasTesting: false,
      frontendType: null,
      frameworks: [],
    }
  }
}

export const syncService = new SyncService()
export { SyncService }
export type { ProjectSyncResult as SyncResult } from '../types/project-sync'
