/**
 * Issue Enricher
 * Generates rich context for issues using AI analysis of the codebase.
 *
 * This module provides prompts and templates for Claude to enrich issues.
 * The actual AI call happens through Claude Code's execution context.
 */

import { getErrorMessage } from '../../types/fs'
import type { EnrichedIssue, Issue } from './types'

// =============================================================================
// Enrichment Templates
// =============================================================================

/**
 * Generate enrichment prompt
 * This prompt can be used with any AI assistant (Claude, ChatGPT, Copilot, Gemini, etc.)
 */
export function generateEnrichmentPrompt(issue: Issue, projectContext: ProjectContext): string {
  return `
# Issue Enrichment Request

## Original Issue
- **ID**: ${issue.externalId}
- **Title**: ${issue.title}
- **Type**: ${issue.type}
- **Priority**: ${issue.priority}
- **Current Description**: ${issue.description || '(no description provided)'}
- **Labels**: ${issue.labels.join(', ') || 'none'}
- **Team**: ${issue.team?.name || 'unknown'}

## Project Context
- **Project**: ${projectContext.name}
- **Tech Stack**: ${projectContext.techStack.join(', ')}
- **Key Directories**: ${projectContext.keyDirectories.join(', ')}

## Your Task

Analyze this issue and the codebase to generate comprehensive enrichment.

### 1. Enhanced Description
Write a clear, detailed description that includes:
- What the user/stakeholder is trying to achieve
- Why this change is needed
- Any relevant context from similar features in the codebase

### 2. Acceptance Criteria
Generate 3-7 specific, testable acceptance criteria in the format:
- [ ] When [action], then [expected result]

### 3. Affected Files
Based on the issue title and codebase analysis, identify files likely to be modified:
- List specific file paths
- Explain why each file is relevant

### 4. Technical Notes
Provide implementation hints:
- Relevant existing patterns to follow
- Potential gotchas or edge cases
- Dependencies or related code

### 5. Complexity Estimate
Rate as: trivial | small | medium | large | epic
Explain your reasoning.

### 6. Suggested Approach (optional)
If there are multiple ways to implement this, suggest the recommended approach.

---

**Format your response as JSON matching the EnrichedIssue.enrichment schema.**
`.trim()
}

/**
 * Generate copy-paste ready LLM prompt
 * Compatible with Claude, ChatGPT, Copilot, Gemini, Cursor, etc.
 */
export function generateLLMPrompt(
  issue: Issue,
  projectContext: ProjectContext,
  enrichment: EnrichmentResult
): string {
  const filesList = enrichment.affectedFiles.map((f) => `- ${f}`).join('\n')

  const acList = enrichment.acceptanceCriteria.map((ac) => `- [ ] ${ac}`).join('\n')

  return `## Task: ${issue.title}

### Context
I'm working on a codebase with the following structure:
- Stack: ${projectContext.techStack.join(', ')}
- Key directories: ${projectContext.keyDirectories.join(', ')}

### Problem
${enrichment.description}

### What needs to be done
${enrichment.technicalNotes}

### Files to modify
${filesList || '(analyze codebase to identify)'}

### Reference implementation
${enrichment.suggestedApproach || 'Follow existing patterns in the codebase.'}

### Acceptance criteria
${acList}

### How to verify
1. Run tests to ensure nothing is broken
2. Manually test the affected functionality
3. Review code for edge cases

---
*Generated by prjct - Use with any AI assistant*
`.trim()
}

// =============================================================================
// Types
// =============================================================================

export interface ProjectContext {
  name: string
  techStack: string[]
  keyDirectories: string[]
  recentCommits?: string[]
  patterns?: Record<string, string>
}

export interface EnrichmentResult {
  description: string
  acceptanceCriteria: string[]
  affectedFiles: string[]
  technicalNotes: string
  estimatedComplexity: 'trivial' | 'small' | 'medium' | 'large' | 'epic'
  suggestedApproach?: string
  relatedCode?: Array<{ file: string; relevance: string }>
}

// =============================================================================
// Enrichment Helpers
// =============================================================================

/**
 * Build enriched issue from result
 */
export function buildEnrichedIssue(issue: Issue, enrichment: EnrichmentResult): EnrichedIssue {
  return {
    ...issue,
    enrichment: {
      ...enrichment,
      generatedAt: new Date().toISOString(),
    },
  }
}

/**
 * Format enrichment as markdown for updating issue description
 */
export function formatEnrichmentAsMarkdown(enrichment: EnrichmentResult): string {
  const sections: string[] = []

  // Description
  sections.push(enrichment.description)
  sections.push('')

  // Acceptance Criteria
  sections.push('## Acceptance Criteria')
  for (const ac of enrichment.acceptanceCriteria) {
    sections.push(`- [ ] ${ac}`)
  }
  sections.push('')

  // Technical Notes
  if (enrichment.technicalNotes) {
    sections.push('## Technical Notes')
    sections.push(enrichment.technicalNotes)
    sections.push('')
  }

  // Affected Files
  if (enrichment.affectedFiles.length > 0) {
    sections.push('## Affected Files')
    for (const file of enrichment.affectedFiles) {
      sections.push(`- \`${file}\``)
    }
    sections.push('')
  }

  // Complexity
  sections.push(`**Estimated Complexity**: ${enrichment.estimatedComplexity}`)

  // Footer
  sections.push('')
  sections.push('---')
  sections.push('*Enriched by prjct*')

  return sections.join('\n')
}

/**
 * Parse JSON enrichment response from Claude
 */
export function parseEnrichmentResponse(response: string): EnrichmentResult | null {
  try {
    // Extract JSON from response (may be wrapped in markdown code block)
    const jsonMatch =
      response.match(/```(?:json)?\s*([\s\S]*?)```/) || response.match(/\{[\s\S]*\}/)

    if (!jsonMatch) {
      console.error('[enricher] No JSON found in response')
      return null
    }

    const jsonStr = jsonMatch[1] || jsonMatch[0]
    const parsed = JSON.parse(jsonStr)

    // Validate required fields
    if (!parsed.description || !parsed.acceptanceCriteria || !parsed.estimatedComplexity) {
      console.error('[enricher] Missing required fields in enrichment')
      return null
    }

    return {
      description: parsed.description,
      acceptanceCriteria: Array.isArray(parsed.acceptanceCriteria) ? parsed.acceptanceCriteria : [],
      affectedFiles: Array.isArray(parsed.affectedFiles) ? parsed.affectedFiles : [],
      technicalNotes: parsed.technicalNotes || '',
      estimatedComplexity: parsed.estimatedComplexity,
      suggestedApproach: parsed.suggestedApproach,
      relatedCode: parsed.relatedCode,
    }
  } catch (error) {
    console.error('[enricher] Failed to parse enrichment:', getErrorMessage(error))
    return null
  }
}

// =============================================================================
// Quick Enrichment (Minimal AI)
// =============================================================================

/**
 * Generate basic enrichment without full AI analysis
 * Useful for quick syncs or when AI is unavailable
 */
export function generateQuickEnrichment(issue: Issue): EnrichmentResult {
  const typeToComplexity: Record<string, 'trivial' | 'small' | 'medium' | 'large'> = {
    bug: 'small',
    chore: 'trivial',
    task: 'small',
    improvement: 'medium',
    feature: 'medium',
    epic: 'large',
  }

  return {
    description: issue.description || `Implement: ${issue.title}`,
    acceptanceCriteria: [
      `The ${issue.type} "${issue.title}" is implemented`,
      'All existing tests pass',
      'New functionality is tested',
    ],
    affectedFiles: [],
    technicalNotes: 'Analyze codebase to identify affected files and implementation approach.',
    estimatedComplexity: typeToComplexity[issue.type] || 'medium',
  }
}
