/**
 * Conductor Integration
 *
 * Detects and integrates with Conductor (conductor.build) for
 * multi-agent parallel sessions. Scaffolds conductor.json and
 * setup/teardown scripts for workspace lifecycle management.
 *
 * @module integrations/conductor
 */

import fs from 'node:fs/promises'
import path from 'node:path'
import { fileExists } from '../utils/file-helper'

// =============================================================================
// Types
// =============================================================================

interface ConductorConfig {
  scripts?: {
    setup?: string
    run?: string
    archive?: string
  }
  runScriptMode?: 'concurrent' | 'nonconcurrent'
}

// =============================================================================
// Conductor Integration
// =============================================================================

class ConductorIntegration {
  /**
   * Detect if the project has a conductor.json
   */
  async detect(projectPath: string): Promise<boolean> {
    return fileExists(path.join(projectPath, 'conductor.json'))
  }

  /**
   * Read conductor.json if it exists
   */
  async readConfig(projectPath: string): Promise<ConductorConfig | null> {
    try {
      const configPath = path.join(projectPath, 'conductor.json')
      const content = await fs.readFile(configPath, 'utf-8')
      return JSON.parse(content)
    } catch {
      return null
    }
  }

  /**
   * Scaffold conductor.json + bin/dev-setup + bin/dev-teardown
   */
  async scaffold(projectPath: string): Promise<{ files: string[] }> {
    const files: string[] = []

    // Detect package manager
    const hasBun = await fileExists(path.join(projectPath, 'bun.lockb'))
    const hasPnpm = await fileExists(path.join(projectPath, 'pnpm-lock.yaml'))
    const installCmd = hasBun ? 'bun install' : hasPnpm ? 'pnpm install' : 'npm install'

    // Write conductor.json
    const conductorJson: ConductorConfig = {
      scripts: {
        setup: 'bin/dev-setup',
        archive: 'bin/dev-teardown',
      },
    }
    const conductorPath = path.join(projectPath, 'conductor.json')
    if (!(await fileExists(conductorPath))) {
      await fs.writeFile(conductorPath, `${JSON.stringify(conductorJson, null, 2)}\n`)
      files.push('conductor.json')
    }

    // Create bin directory
    const binDir = path.join(projectPath, 'bin')
    await fs.mkdir(binDir, { recursive: true })

    // Write bin/dev-setup
    const setupPath = path.join(binDir, 'dev-setup')
    if (!(await fileExists(setupPath))) {
      await fs.writeFile(
        setupPath,
        [
          '#!/bin/bash',
          '# Conductor workspace setup — auto-generated by prjct',
          'set -euo pipefail',
          '',
          '# Copy .env from main worktree',
          'MAIN=$(git worktree list --porcelain | head -1 | sed "s/worktree //")',
          '[ -f "$MAIN/.env" ] && cp "$MAIN/.env" .env',
          '',
          '# Install dependencies',
          installCmd,
          '',
          '# Symlink .prjct config so all worktrees share the same projectId',
          '[ -d "$MAIN/.prjct" ] && [ ! -e ".prjct" ] && ln -s "$MAIN/.prjct" .prjct',
          '',
          'echo "Workspace ready"',
          '',
        ].join('\n')
      )
      await fs.chmod(setupPath, 0o755)
      files.push('bin/dev-setup')
    }

    // Write bin/dev-teardown
    const teardownPath = path.join(binDir, 'dev-teardown')
    if (!(await fileExists(teardownPath))) {
      await fs.writeFile(
        teardownPath,
        [
          '#!/bin/bash',
          '# Conductor workspace teardown — auto-generated by prjct',
          'set -euo pipefail',
          '',
          'echo "Workspace archived"',
          '',
        ].join('\n')
      )
      await fs.chmod(teardownPath, 0o755)
      files.push('bin/dev-teardown')
    }

    return { files }
  }
}

// =============================================================================
// Singleton
// =============================================================================

export const conductorIntegration = new ConductorIntegration()
export default conductorIntegration
