/**
 * Agentic Types
 * Types for the agentic system.
 */

import type { Plan } from './agentic/plan-execution'
import type { CommandParams, ContextPaths } from './core'

// Input Source Types (PRJ-102)

/**
 * Source of context data - tracks origin for traceability.
 * Pattern from Anthropic: always track where data comes from.
 *
 * @see PRJ-102
 */
export type InputSource =
  | 'user_explicit' // User directly provided this (e.g., task description, idea)
  | 'user_file' // From a user-created file (e.g., PRJCT.md, custom agents)
  | 'system_detected' // Automatically detected (e.g., stack detection, git analysis)
  | 'system_generated' // Generated by the system (e.g., now.md, analysis)
  | 'system_inferred' // Inferred from other data (e.g., domain detection)
  | 'learned' // Learned from patterns/history
  | 'external' // From external service (e.g., Linear, JIRA)
  | 'inherited' // Inherited from parent context (monorepo)
  | 'cached' // From cache (may be stale)
  | 'unknown' // Source not tracked (legacy data)

/**
 * Metadata about data source and freshness.
 */
export interface SourceMetadata {
  /** Where this data came from */
  source: InputSource
  /** When this was captured/detected */
  capturedAt: string
  /** Confidence in this data (0-1) */
  confidence?: number
  /** Path to source file if applicable */
  sourcePath?: string
  /** Whether this might be stale */
  mayBeStale?: boolean
}

/**
 * Base interface for any item with source tracking.
 */
export interface SourcedItem {
  /** Metadata about where this item came from */
  _source?: SourceMetadata
}

// Tool Registry Types

export type ToolFunction = (...args: unknown[]) => Promise<unknown>

export interface ToolRegistryInterface {
  tools: Map<string, ToolFunction>
  register(name: string, fn: ToolFunction): void
  get(name: string): ToolFunction | undefined
  isAllowed(name: string, allowedTools: string[]): boolean
  list(): string[]
}

export interface ToolDefinition {
  name: string
  description: string
  handler: ToolFunction
  parallelizable: boolean
}

export interface ToolRegistry {
  get(name: string): ToolFunction | undefined
  list(): string[]
  has(name: string): boolean
}

// Context Types

export type ContextDomain = string

export interface ContextState {
  [key: string]: string | null
}

export interface SmartContextProjectState {
  projectId: string
  currentTask: { description: string; startedAt: string } | null
  queue: { description: string; priority: string }[]
}

export interface FullContext {
  state: SmartContextProjectState | null
  roadmap: FeatureInfo[]
  patterns: PatternInfo[]
  stack: StackInfo
  files: string[]
  projectPath: string
}

export interface FilteredContext {
  roadmap: FeatureInfo[]
  patterns: PatternInfo[]
  stack: Partial<StackInfo>
  files: string[]
  metrics: FilterMetrics
}

export interface FeatureInfo extends SourcedItem {
  id: string
  name: string
  relatedTo: ContextDomain[]
  status: string
}

export interface PatternInfo extends SourcedItem {
  description: string
  domain: ContextDomain
  confidence: number
}

export interface StackInfo {
  frontend: string[]
  backend: string[]
  devops: string[]
  database: string[]
  testing: string[]
}

export interface FilterMetrics {
  originalSize: number
  filteredSize: number
  reductionPercent: number
  domain: ContextDomain
}

export interface DomainAnalysis {
  primary: ContextDomain
  secondary: ContextDomain[]
  confidence: number
}

// Prompt Builder Types

export interface PromptProjectState {
  projectId: string
  currentTask: { description: string; startedAt: string; estimate?: string } | null
  queue: { description: string; priority: string }[]
}

export interface Frontmatter {
  name?: string
  description?: string
  'allowed-tools'?: string[]
  [key: string]: unknown
}

export interface Template {
  frontmatter: Frontmatter
  content: string
}

export interface PromptAgent {
  name: string
  role?: string
  skills?: string[]
  [key: string]: unknown
}

export interface PromptContext {
  files?: string[]
  filteredSize?: number
  projectPath?: string
  projectId?: string
  params?: { task?: string; description?: string }
  [key: string]: unknown
}

export interface PromptState {
  codePatterns?: string
  analysis?: string
  [key: string]: unknown
}

export interface ThinkBlock {
  plan?: string[]
  conclusions?: string[]
  confidence?: number
}

export interface PlanInfo {
  isPlanning?: boolean
  requiresApproval?: boolean
  allowedTools?: string[]
  active?: Plan | null
}

// Ground Truth Types

/**
 * Context for ground truth verification.
 * Compatible with ProjectContext - can be passed directly from contextBuilder.build()
 */
export interface GroundTruthContext {
  projectPath: string
  projectId: string | null
  paths: ContextPaths
  params: CommandParams
}

export interface VerificationResult {
  verified: boolean
  actual: Record<string, unknown>
  warnings: string[]
  recommendations: string[]
}

export type Verifier = (context: GroundTruthContext, state: unknown) => Promise<VerificationResult>
