/**
 * Agentic Types
 * Types for the agentic system.
 */

import type { CommandParams, ContextPaths } from './core'

// =============================================================================
// Input Source Types (PRJ-102)
// =============================================================================

/**
 * Source of context data - tracks origin for traceability.
 * Pattern from Anthropic: always track where data comes from.
 *
 * @see PRJ-102
 */
export type InputSource =
  | 'user_explicit' // User directly provided this (e.g., task description, idea)
  | 'user_file' // From a user-created file (e.g., PRJCT.md, custom agents)
  | 'system_detected' // Automatically detected (e.g., stack detection, git analysis)
  | 'system_generated' // Generated by the system (e.g., now.md, analysis)
  | 'system_inferred' // Inferred from other data (e.g., domain detection)
  | 'learned' // Learned from patterns/history
  | 'external' // From external service (e.g., Linear, JIRA)
  | 'inherited' // Inherited from parent context (monorepo)
  | 'cached' // From cache (may be stale)
  | 'unknown' // Source not tracked (legacy data)

/**
 * Metadata about data source and freshness.
 */
export interface SourceMetadata {
  /** Where this data came from */
  source: InputSource
  /** When this was captured/detected */
  capturedAt: string
  /** Confidence in this data (0-1) */
  confidence?: number
  /** Path to source file if applicable */
  sourcePath?: string
  /** Whether this might be stale */
  mayBeStale?: boolean
}

/**
 * Base interface for any item with source tracking.
 */
export interface SourcedItem {
  /** Metadata about where this item came from */
  _source?: SourceMetadata
}

/**
 * Create source metadata with current timestamp.
 */
export function createSourceMetadata(
  source: InputSource,
  options: Partial<Omit<SourceMetadata, 'source'>> = {}
): SourceMetadata {
  return {
    source,
    capturedAt: new Date().toISOString(),
    ...options,
  }
}

// =============================================================================
// Tool Registry Types
// =============================================================================

export type ToolFunction = (...args: unknown[]) => Promise<unknown>

export interface ToolRegistryInterface {
  tools: Map<string, ToolFunction>
  register(name: string, fn: ToolFunction): void
  get(name: string): ToolFunction | undefined
  isAllowed(name: string, allowedTools: string[]): boolean
  list(): string[]
}

export interface ToolDefinition {
  name: string
  description: string
  handler: ToolFunction
  parallelizable: boolean
}

export interface ToolRegistry {
  get(name: string): ToolFunction | undefined
  list(): string[]
  has(name: string): boolean
}

export interface BashResult {
  stdout: string
  stderr: string
  code: number
}

// =============================================================================
// Context Types
// =============================================================================

export type ContextDomain = 'frontend' | 'backend' | 'devops' | 'docs' | 'testing' | 'general'

export interface ContextState {
  [key: string]: string | null
}

export interface SmartContextProjectState {
  projectId: string
  currentTask: { description: string; startedAt: string } | null
  queue: { description: string; priority: string }[]
}

export interface FullContext {
  state: SmartContextProjectState | null
  roadmap: FeatureInfo[]
  patterns: PatternInfo[]
  stack: StackInfo
  files: string[]
  projectPath: string
}

export interface FilteredContext {
  roadmap: FeatureInfo[]
  patterns: PatternInfo[]
  stack: Partial<StackInfo>
  files: string[]
  metrics: FilterMetrics
}

export interface FeatureInfo extends SourcedItem {
  id: string
  name: string
  relatedTo: ContextDomain[]
  status: string
}

export interface PatternInfo extends SourcedItem {
  description: string
  domain: ContextDomain
  confidence: number
}

export interface StackInfo {
  frontend: string[]
  backend: string[]
  devops: string[]
  database: string[]
  testing: string[]
}

export interface FilterMetrics {
  originalSize: number
  filteredSize: number
  reductionPercent: number
  domain: ContextDomain
}

export interface DomainAnalysis {
  primary: ContextDomain
  secondary: ContextDomain[]
  confidence: number
}

// =============================================================================
// Prompt Builder Types
// =============================================================================

export interface PromptProjectState {
  projectId: string
  currentTask: { description: string; startedAt: string; estimate?: string } | null
  queue: { description: string; priority: string }[]
}

export interface Frontmatter {
  name?: string
  description?: string
  'allowed-tools'?: string[]
  [key: string]: unknown
}

export interface Template {
  frontmatter: Frontmatter
  content: string
}

export interface PromptAgent {
  name: string
  role?: string
  skills?: string[]
  [key: string]: unknown
}

export interface PromptContext {
  files?: string[]
  filteredSize?: number
  projectPath?: string
  projectId?: string
  params?: { task?: string; description?: string }
  [key: string]: unknown
}

export interface PromptState {
  codePatterns?: string
  analysis?: string
  [key: string]: unknown
}

/**
 * Learned patterns from memory (Record version)
 */
export type LearnedPatternsRecord = Record<string, string | null>

export interface ThinkBlock {
  plan?: string[]
  conclusions?: string[]
  confidence?: number
}

export interface PlanInfo {
  isPlanning?: boolean
  requiresApproval?: boolean
  allowedTools?: string[]
  active?: Plan | null
}

// =============================================================================
// Ground Truth Types
// =============================================================================

/**
 * Context for ground truth verification.
 * Compatible with ProjectContext - can be passed directly from contextBuilder.build()
 */
export interface GroundTruthContext {
  projectPath: string
  projectId: string | null
  paths: ContextPaths
  params: CommandParams
}

export interface VerificationResult {
  verified: boolean
  actual: Record<string, unknown>
  warnings: string[]
  recommendations: string[]
}

export type Verifier = (context: GroundTruthContext, state: unknown) => Promise<VerificationResult>

// =============================================================================
// Plan Mode Types
// =============================================================================

export interface PlanParams extends CommandParams {
  /** Skip approval prompt */
  autoApprove?: boolean
  /** Verbose output during planning */
  verbose?: boolean
}

export interface GatheredInfo extends SourcedItem {
  type: GatheredInfoType
  /** Path or identifier of the source */
  source: string
  data: string | GatheredFileData | GatheredAnalysisData
  gatheredAt: string
  /** Input source category for traceability */
  inputSource?: InputSource
}

export type GatheredInfoType =
  | 'file_content'
  | 'git_status'
  | 'git_diff'
  | 'analysis'
  | 'dependencies'
  | 'structure'

export interface GatheredFileData {
  path: string
  content: string
  lines: number
}

export interface GatheredAnalysisData {
  summary: string
  findings: string[]
}

export interface ProposedPlan {
  summary: string
  approach: string
  steps: PlanStepDefinition[]
  risks?: string[]
  alternatives?: string[]
  estimatedTime?: string
  affectedFiles: string[]
}

export interface PlanStepDefinition {
  description: string
  tool?: string
  args?: string[]
}

export interface PlanStep {
  index: number
  description: string
  status: 'pending' | 'completed' | 'failed'
  tool?: string
  args?: string[]
  result?: PlanStepResult
  completedAt?: string
  error?: string
}

export interface PlanStepResult {
  success: boolean
  output?: string
  filesModified?: string[]
}

export type PlanStatus =
  | 'gathering'
  | 'analyzing'
  | 'proposing'
  | 'awaiting_approval'
  | 'approved'
  | 'rejected'
  | 'executing'
  | 'completed'
  | 'aborted'

export interface Plan {
  id: string
  projectId: string
  command: string
  params: PlanParams
  status: PlanStatus
  startedAt: string
  gatheredInfo: GatheredInfo[]
  analysis: PlanAnalysis | null
  proposedPlan: ProposedPlan | null
  userFeedback: string | null
  approvedAt: string | null
  executionStartedAt: string | null
  completedAt: string | null
  steps: PlanStep[]
  currentStep: number
  abortReason?: string
}

export interface PlanAnalysis {
  complexity: 'low' | 'medium' | 'high'
  riskLevel: 'low' | 'medium' | 'high'
  estimatedDuration: string
  dependencies: string[]
}

export interface ApprovalPrompt {
  title: string
  message: string
  details?: string[]
  options: ApprovalOption[]
}

export interface ApprovalOption {
  key: string
  label: string
  action: 'approve' | 'reject' | 'modify' | 'abort' | 'edit' | 'list'
}

export interface ApprovalContext {
  branch?: string
  changedFiles: ChangedFile[]
  commitMessage?: string
  filesToDelete: string[]
  linesOfCode?: number
  operation: ApprovalOperation
  warnings: string[]
}

export interface ChangedFile {
  path: string
  action: 'create' | 'modify' | 'delete'
  linesAdded?: number
  linesRemoved?: number
}

export type ApprovalOperation =
  | 'create_files'
  | 'modify_files'
  | 'delete_files'
  | 'git_commit'
  | 'git_push'
  | 'run_command'

// =============================================================================
// Loop Detector Types
// =============================================================================

export interface ErrorEntry {
  message: string
  timestamp: number
}

export interface AttemptRecord {
  command: string
  context: string
  attempts: number
  errors: ErrorEntry[]
  firstAttempt: number
  lastAttempt: number
  success: boolean
}

export interface ErrorPattern {
  type: string
  description: string
}

export interface EscalationInfo {
  status: string
  command: string
  context: string
  attempts: number
  duration: number
  errorPattern: ErrorPattern
  message: string
  suggestion: string
  lastError: string | null
}

export interface AttemptResult {
  success?: boolean
  error?: string
}

export interface AttemptInfo {
  attemptNumber: number
  isLooping: boolean
  shouldEscalate: boolean
}

export interface HallucinationPattern {
  pattern: RegExp
  type: string
  description: string
}

export interface HallucinationResult {
  detected: boolean
  type?: string
  pattern?: string
  description?: string
  message?: string
  suggestion?: string
}

export interface OutputAnalysis extends HallucinationResult {
  shouldBlock: boolean
  action?: string
}

// =============================================================================
// Command Executor Types
// =============================================================================

export interface ExecutionResult {
  success: boolean
  error?: string
  escalation?: EscalationInfo | null
  isLoopDetected?: boolean
  suggestion?: string
  validation?: unknown
  isValidationError?: boolean
  template?: unknown
  context?: unknown
  state?: unknown
  prompt?: string
  agenticDelegation?: boolean
  agenticMode?: boolean
  agenticExecContext?: unknown
  agenticPrompt?: string
  requiresOrchestration?: boolean
  orchestratorPath?: string
  taskFragmentationPath?: string
  reasoning?: unknown
  thinkBlock?: unknown
  groundTruth?: unknown
  compressionMetrics?: unknown
  learnedPatterns?: unknown
  relevantMemories?: unknown
  orchestratorContext?: OrchestratorContext | null
  formatResponse?: (data: unknown) => string
  formatThinkBlock?: (verbose: boolean) => string
  parallel?: {
    execute: (toolCalls: unknown[]) => Promise<unknown>
    readAll: (paths: string[]) => Promise<Map<string, string | null>>
    canParallelize: (tools: string[]) => boolean
    getMetrics: () => unknown
  }
  memory?: {
    create: (memory: unknown) => Promise<string>
    autoRemember: (type: string, value: string, ctx?: string) => Promise<void>
    search: (query: string) => Promise<unknown[]>
    findByTags: (tags: string[]) => Promise<unknown[]>
    getStats: () => Promise<unknown>
  }
  plan?: {
    active: unknown
    isPlanning: boolean
    isDestructive: boolean
    requiresApproval: boolean
    recordInfo: (info: unknown) => void
    setAnalysis: (analysis: unknown) => void
    propose: (plan: unknown) => unknown
    approve: (feedback?: string | null) => unknown
    reject: (reason?: string | null) => unknown
    getApprovalPrompt: () => unknown
    startExecution: () => unknown
    getNextStep: () => unknown
    completeStep: (result?: unknown) => unknown
    failStep: (error: string) => unknown
    abort: (reason?: string) => unknown
    getStatus: () => string
    getAllowedTools: () => string[]
  }
  attemptNumber?: number
  isLooping?: boolean
}

export interface SimpleExecutionResult {
  success: boolean
  result?: unknown
  error?: string
}

export type ExecutionToolsFn = (
  tools: {
    read: (path: string) => Promise<unknown>
    write: (path: string, content: string) => Promise<unknown>
    bash: (cmd: string) => Promise<unknown>
  },
  context: unknown
) => Promise<unknown>

// =============================================================================
// Template Loader Types
// =============================================================================

export interface ParsedTemplate {
  frontmatter: Frontmatter
  content: string
  raw?: string
}

// =============================================================================
// Skill Loader Types
// =============================================================================

export interface FormattedSkill {
  id?: string
  name: string
  description?: string
  prompt?: string
  content?: string
}

export interface SkillContext {
  skills?: FormattedSkill[]
  availableSkills: FormattedSkill[]
  skillsMarkdown: string
  projectPath?: string
  timestamp?: string
}

// =============================================================================
// Chain of Thought Types
// =============================================================================

export interface ChainOfThoughtContext {
  projectPath?: string
  projectId?: string | null
  paths?: Record<string, string>
  params?: Record<string, unknown>
}

export interface ChainOfThoughtState {
  currentTask?: { description: string; startedAt: string } | null
  queue?: { description: string; priority: string }[]
  [key: string]: unknown
}

export interface ReasoningStep {
  step: string
  result: string
  passed: boolean
}

export interface ReasoningResult {
  steps: ReasoningStep[]
  allPassed: boolean
  plan: string[]
}

export interface ChainOfThoughtResult {
  reasoning: ReasoningResult | null
  thinkBlock: string | null
}

// =============================================================================
// Learned Patterns Type
// =============================================================================

export interface LearnedPatterns {
  commit_footer?: string | null
  branch_naming?: string | null
  test_before_ship?: string | null
  preferred_agent?: string | null
  [key: string]: string | null | undefined
}

// =============================================================================
// Orchestrator Types
// =============================================================================

/**
 * Subtask for task fragmentation
 */
export interface OrchestratorSubtask {
  id: string
  description: string
  domain: string
  agent: string
  status: 'pending' | 'in_progress' | 'completed' | 'failed'
  dependsOn: string[]
  order: number
  /** Handoff from previous subtask — injected into prompt for context continuity (PRJ-262) */
  handoff?: {
    fromSubtask: string
    outputForNextAgent: string
    filesChanged: Array<{ path: string; action: string }>
    whatWasDone: string[]
  }
}

/**
 * Real codebase context gathered proactively before agent execution.
 * Provides git state, relevant files, and code signatures so the agent
 * doesn't need to explore before starting work.
 */
export interface RealCodebaseContext {
  /** Current git branch */
  gitBranch: string
  /** Short git status (e.g., "3 files modified, 1 untracked") */
  gitStatus: string
  /** Files scored by relevance to the task */
  relevantFiles: Array<{ path: string; score: number; reason: string }>
  /** Recently changed files */
  recentFiles: Array<{ path: string; lastChanged: string; changes: number }>
  /** Code signatures from top relevant files */
  signatures: Array<{ path: string; content: string }>
}

/**
 * Full orchestrator context returned after execution
 */
/**
 * Context degradation tracking (PRJ-277).
 * Reports which context tools succeeded/failed so the LLM can adjust behavior.
 */
export interface ContextDegradation {
  /** Overall degradation level */
  level: 'full' | 'partial' | 'minimal'
  /** Names of tools that failed (e.g., 'realContext', 'sealedAnalysis', 'velocity') */
  failedTools: string[]
}

export interface OrchestratorContext {
  /** Domains detected for this task */
  detectedDomains: string[]
  /** Primary domain (most important) */
  primaryDomain: string
  /** Whether task requires fragmentation (3+ domains) */
  requiresFragmentation: boolean
  /** Subtasks if fragmented, null otherwise */
  subtasks: OrchestratorSubtask[] | null
  /** Project info */
  project: {
    id: string
    ecosystem: string
    conventions: string[]
  }
  /** Real codebase context gathered proactively */
  realContext?: RealCodebaseContext
  /** Sealed/active analysis from PRJ-263 storage — injected into prompt context (PRJ-260) */
  sealedAnalysis?: SealedAnalysisContext | null
  /** Velocity context for estimation guidance (PRJ-296) */
  velocityContext?: string | null
  /** Context degradation tracking (PRJ-277) */
  contextDegradation?: ContextDegradation
  /** RPI phase context (research → plan → implement) */
  rpiContext?: RpiContext | null
}

// =============================================================================
// Context Health (Dex Horthy context management)
// =============================================================================

/** Context zone based on usage percentage of input budget */
export type ContextZone = 'smart' | 'warning' | 'dumb'

/** Current context health status with zone and usage metrics */
export interface ContextHealthStatus {
  zone: ContextZone
  usagePercent: number
  usedTokens: number
  budgetTokens: number
  recommendation: string | null
}

/** Records a zone transition event */
export interface ZoneTransition {
  from: ContextZone
  to: ContextZone
  usagePercent: number
  timestamp: string
  action: string | null
}

// =============================================================================
// RPI Flow (Research → Plan → Implement)
// =============================================================================

/** Current phase of the RPI flow */
export type RpiPhase = 'research' | 'plan' | 'implement'

/** Context for the active RPI phase */
export interface RpiContext {
  phase: RpiPhase
  researchDoc?: string
  planDoc?: string
  scopedFiles?: string[]
}

/**
 * Subset of analysis data injected into prompt context.
 * Extracted from AnalysisSchema to avoid coupling types to storage schema.
 *
 * @see PRJ-260
 */
export interface SealedAnalysisContext {
  /** Programming languages detected */
  languages: string[]
  /** Frameworks detected */
  frameworks: string[]
  /** Package manager (e.g., 'bun', 'npm', 'pnpm') */
  packageManager?: string
  /** Source directory */
  sourceDir?: string
  /** Test directory */
  testDir?: string
  /** Total files analyzed */
  fileCount: number
  /** Code patterns found */
  patterns: Array<{ name: string; description: string; location?: string }>
  /** Anti-patterns found */
  antiPatterns: Array<{ issue: string; file: string; suggestion: string }>
  /** Lifecycle status */
  status: 'draft' | 'verified' | 'sealed'
  /** Git commit hash when analysis was performed */
  commitHash?: string
}

// =============================================================================
// Response Validator Types
// =============================================================================

export interface ValidationSuccess<T> {
  success: true
  data: T
}

export interface ValidationFailure {
  success: false
  error: string
  /** Raw parsed JSON (may be partial) */
  rawParsed: unknown
  /** Zod validation issues */
  issues: string[]
}

export type ValidationResult<T> = ValidationSuccess<T> | ValidationFailure

// =============================================================================
// Token Budget Types
// =============================================================================

/** Budget category identifiers ordered by priority */
export type BudgetCategory = 'state' | 'injection' | 'files'

/** Budget allocation result for each category */
export interface BudgetAllocation {
  state: number
  injection: number
  files: number
  inputBudget: number
  outputReserve: number
  contextWindow: number
}

/** Usage tracking per category */
export interface BudgetUsage {
  category: BudgetCategory
  allocated: number
  used: number
  remaining: number
}

// =============================================================================
// Agentic Services Types
// =============================================================================

/**
 * Re-exported from core/agentic/services.ts.
 * Import the actual `AgenticServices` from there for its `typeof` members.
 */

// =============================================================================
// Hook Types
// =============================================================================

export type HookPoint = string

// =============================================================================
// Context Builder Convenience Aliases
// =============================================================================

// Note: Paths, Context, State are re-exports of ContextPaths, ProjectContext,
// ContextState from core/types/core and core/types/agentic respectively.

// =============================================================================
// Anti-Hallucination Types
// =============================================================================

export interface ProjectGroundTruth {
  /** Project root path */
  projectPath: string
  /** Programming language (e.g., 'TypeScript', 'JavaScript', 'Python') */
  language?: string
  /** Primary framework (e.g., 'Hono', 'Next.js', 'Express') */
  framework?: string
  /** Technology stack items (e.g., ['Hono', 'Zod', 'Vitest']) */
  techStack?: string[]
  /** Domain flags from sealed analysis */
  domains?: {
    hasFrontend?: boolean
    hasBackend?: boolean
    hasDatabase?: boolean
    hasTesting?: boolean
    hasDocker?: boolean
  }
  /** Total files in project */
  fileCount?: number
  /** Sealed analysis languages — used to ground available tech (PRJ-260) */
  analysisLanguages?: string[]
  /** Sealed analysis frameworks — used to ground available tech (PRJ-260) */
  analysisFrameworks?: string[]
  /** Package manager from sealed analysis (PRJ-260) */
  analysisPackageManager?: string
}

// =============================================================================
// Environment Block Types
// =============================================================================

export interface EnvironmentBlockInput {
  /** Project display name */
  projectName: string
  /** Absolute path to project root */
  projectPath: string
  /** Whether the project is a git repository */
  isGitRepo?: boolean
  /** Current git branch name */
  gitBranch?: string
  /** Operating system platform (auto-detected if not provided) */
  platform?: string
  /** JavaScript runtime (auto-detected if not provided) */
  runtime?: string
  /** Current date in ISO format (auto-generated if not provided) */
  date?: string
  /** AI model identifier (e.g., 'opus', 'sonnet', '2.5-pro') */
  model?: string
  /** AI provider name (e.g., 'claude', 'gemini', 'cursor') */
  provider?: string
}

// =============================================================================
// Prompt Builder Types (Section Priority)
// =============================================================================

/**
 * Prompt section priorities for budget trimming.
 */
export type SectionPriority = 'critical' | 'important' | 'optional'

// =============================================================================
// Injection Validator Types
// =============================================================================

/** Configurable token budgets per injection section */
export interface InjectionBudgets {
  /** Auto-injected context (task + queue + patterns) */
  autoContext: number
  /** State data section */
  stateData: number
  /** Memories section */
  memories: number
  /** Total prompt ceiling (all sections combined) */
  totalPrompt: number
}

// =============================================================================
// Template Executor Types
// =============================================================================

export interface TemplateExecutionContext {
  projectPath: string
  projectId: string
  globalPath: string
  command: string
  args: string

  // Agent information
  agentName: string
  agentSettingsPath: string

  // Paths for execution (not content)
  paths: {
    orchestrator: string
    taskFragmentation: string
    commandTemplate: string
    repoAnalysis: string
    skillsDir: string
    stateJson: string
  }
}

export interface AgenticPromptInfo {
  prompt: string
  context: TemplateExecutionContext
  requiresOrchestration: boolean
}

// =============================================================================
// Domain Classifier Types
// =============================================================================

export interface DomainClassifierProjectContext {
  /** Domains detected during sync */
  domains: {
    hasFrontend: boolean
    hasBackend: boolean
    hasDatabase: boolean
    hasTesting: boolean
    hasDocker: boolean
  }
  /** Project stack info */
  stack?: { language?: string; framework?: string }
}

// =============================================================================
// Smart Context Types
// =============================================================================

export type ProjectState = SmartContextProjectState
