/**
 * Context Sync - Generates dynamic project context for Claude
 *
 * Creates ~/.prjct-cli/projects/{id}/CLAUDE.md with:
 * - Stack info
 * - Available agents (dynamic, varies per project)
 * - Current task
 * - Priority queue
 *
 * Called by: /p:sync, /p:analyze, /p:init
 */

const fs = require('fs').promises
const path = require('path')
const os = require('os')

/**
 * Generate project context file for Claude
 * 100% DYNAMIC - reads whatever agents exist
 *
 * @param {string} projectPath - Local project path
 * @param {string} projectId - Project ID from config
 * @returns {Promise<{agents: string[], stack: string|null, currentTask: string|null}>}
 */
async function generateLocalContext(projectPath, projectId) {
  const globalPath = path.join(os.homedir(), '.prjct-cli/projects', projectId)

  // 1. Read ALL agents that exist (dynamic - varies per project)
  const agentsDir = path.join(globalPath, 'agents')
  let agentFiles = []
  try {
    agentFiles = await fs.readdir(agentsDir)
    agentFiles = agentFiles.filter(f => f.endsWith('.md'))
  } catch {
    // No agents directory yet
  }

  // 2. Read core files (may not exist)
  const readSafe = async (p) => {
    try {
      return await fs.readFile(p, 'utf-8')
    } catch {
      return null
    }
  }

  const [repoSummary, now, next, roadmap] = await Promise.all([
    readSafe(path.join(globalPath, 'analysis/repo-summary.md')),
    readSafe(path.join(globalPath, 'core/now.md')),
    readSafe(path.join(globalPath, 'core/next.md')),
    readSafe(path.join(globalPath, 'planning/roadmap.md'))
  ])

  // 3. Extract stack from repo-summary
  const stack = extractStack(repoSummary)

  // 4. Generate agent list with clean names
  const agents = agentFiles.map(f => f.replace('.md', ''))

  // 5. Extract current task
  const currentTask = extractCurrentTask(now)

  // 6. Extract top 3 from next.md
  const nextTasks = extractTopTasks(next, 3)

  // 7. Extract active features from roadmap
  const activeFeatures = extractActiveFeatures(roadmap)

  // 8. Generate CLAUDE.md content
  const content = `# Project Context
<!-- Auto-generated by /p:sync - DO NOT EDIT -->
<!-- projectId: ${projectId} -->
<!-- Last sync: ${new Date().toISOString()} -->

## Stack
${stack || 'Run /p:analyze to detect stack'}

## Available Agents
${agents.length ? agents.map(a => `- ${a}`).join('\n') : 'None. Run /p:sync to generate.'}

## Current Task
${currentTask || 'None. Use /p:now to start.'}

## Next Up
${nextTasks.length ? nextTasks.map((t, i) => `${i + 1}. ${t}`).join('\n') : 'Empty queue.'}

## Active Features
${activeFeatures.length ? activeFeatures.map(f => `- ${f}`).join('\n') : 'None in progress.'}

## Data Location
All project data: ~/.prjct-cli/projects/${projectId}/
- agents/ - Read for detailed patterns and code examples
- analysis/repo-summary.md - Full technical analysis
- planning/roadmap.md - Features and roadmap
`

  // 9. Write to global storage (NOT in repo)
  const contextPath = path.join(globalPath, 'CLAUDE.md')
  await fs.writeFile(contextPath, content, 'utf-8')

  return { agents, stack, currentTask }
}

/**
 * Extract stack from repo-summary
 */
function extractStack(summary) {
  if (!summary) return null

  // Try multiple patterns
  const patterns = [
    /\*\*(?:Stack|Framework|Language)\*\*[:\s|]+([^\n|]+)/i,
    /\| \*\*Type\*\* \| ([^\|]+) \|/i,
    /## Tech Stack[\s\S]*?### (?:Frontend|Backend)\n- \*\*([^*]+)\*\*/i
  ]

  for (const pattern of patterns) {
    const match = summary.match(pattern)
    if (match) return match[1].trim()
  }

  return null
}

/**
 * Extract current task from now.md
 */
function extractCurrentTask(now) {
  if (!now) return null

  // Skip headers and empty lines, get first content line
  const lines = now.split('\n')
  for (const line of lines) {
    const trimmed = line.trim()
    if (trimmed && !trimmed.startsWith('#') && !trimmed.startsWith('<!--')) {
      return trimmed
    }
  }
  return null
}

/**
 * Extract top N tasks from next.md
 */
function extractTopTasks(next, count) {
  if (!next) return []

  return next
    .split('\n')
    .filter(l => l.match(/^[-*\d.]\s/))
    .slice(0, count)
    .map(l => l.replace(/^[-*\d.]\s+/, '').trim())
    .filter(Boolean)
}

/**
 * Extract active features from roadmap.md
 */
function extractActiveFeatures(roadmap) {
  if (!roadmap) return []

  const features = []
  const lines = roadmap.split('\n')
  let inActive = false

  for (const line of lines) {
    if (line.includes('Active') || line.includes('In Progress')) {
      inActive = true
      continue
    }
    if (line.startsWith('## ') && inActive) {
      break // End of active section
    }
    if (inActive && line.match(/^- \[ \]/)) {
      const feature = line.replace(/^- \[ \]\s*\*\*/, '').replace(/\*\*.*$/, '').trim()
      if (feature) features.push(feature)
    }
  }

  return features.slice(0, 3) // Max 3
}

module.exports = { generateLocalContext }
