/**
 * Context Sync - Generates RICH dynamic project context for Claude
 *
 * Creates ~/.prjct-cli/projects/{id}/CLAUDE.md with:
 * - Full stack info (languages, frameworks, dependencies)
 * - Project structure and stats
 * - Agent expertise summaries
 * - Current task and priority queue
 * - Active features from roadmap
 *
 * GOAL: Give Claude ALL the context it needs WITHOUT extra file reads
 *
 * Called by: /p:sync, /p:analyze, /p:init
 */

import fs from 'fs/promises'
import path from 'path'
import os from 'os'

interface StackInfo {
  primary: string | null
  full: string | null
  languages: string[]
  frameworks: string[]
  dependencies: string[]
}

interface ProjectStructure {
  fileCount: number | null
  directories: string[]
}

interface GitCommit {
  hash: string
  message: string
}

interface GitStats {
  commits: number | null
  contributors: number | null
  recentCommits: GitCommit[]
}

interface AgentExpertise {
  name: string
  role: string
  expertise: string
}

interface ContextResult {
  agents: string[]
  stack: StackInfo
  currentTask: string | null
}

/**
 * Generate RICH project context file for Claude
 * Embeds key information so Claude doesn't need to read multiple files
 */
async function generateLocalContext(projectPath: string, projectId: string): Promise<ContextResult> {
  const globalPath = path.join(os.homedir(), '.prjct-cli/projects', projectId)
  const projectName = path.basename(projectPath)

  // Helper to read files safely
  const readSafe = async (p: string): Promise<string | null> => {
    try {
      return await fs.readFile(p, 'utf-8')
    } catch {
      return null
    }
  }

  // 1. Read ALL data sources in parallel
  const agentsDir = path.join(globalPath, 'agents')
  let agentFiles: string[] = []
  try {
    agentFiles = await fs.readdir(agentsDir)
    agentFiles = agentFiles.filter(f => f.endsWith('.md'))
  } catch {
    // No agents directory yet
  }

  const [repoSummary, now, next, roadmap, ideas] = await Promise.all([
    readSafe(path.join(globalPath, 'analysis/repo-summary.md')),
    readSafe(path.join(globalPath, 'core/now.md')),
    readSafe(path.join(globalPath, 'core/next.md')),
    readSafe(path.join(globalPath, 'planning/roadmap.md')),
    readSafe(path.join(globalPath, 'planning/ideas.md'))
  ])

  // 2. Extract RICH stack info from repo-summary
  const stackInfo = extractFullStack(repoSummary)

  // 3. Extract project structure from repo-summary
  const projectStructure = extractProjectStructure(repoSummary)

  // 4. Extract git stats
  const gitStats = extractGitStats(repoSummary)

  // 5. Read agent expertise (just the key parts, not full templates)
  const agentExpertise = await extractAgentExpertise(agentsDir, agentFiles)

  // 6. Extract current task
  const currentTask = extractCurrentTask(now)

  // 7. Extract priority queue (top 5)
  const nextTasks = extractTopTasks(next, 5)

  // 8. Extract active features from roadmap
  const activeFeatures = extractActiveFeatures(roadmap)

  // 9. Extract recent ideas
  const recentIdeas = extractRecentIdeas(ideas)

  // 10. Generate RICH CLAUDE.md content
  const content = `# ${projectName} - Project Context
<!-- Auto-generated by /p:sync - DO NOT EDIT MANUALLY -->
<!-- projectId: ${projectId} -->
<!-- Last sync: ${new Date().toISOString()} -->

## Quick Reference

| Attribute | Value |
|-----------|-------|
| **Project** | ${projectName} |
| **Stack** | ${stackInfo.primary || 'Not detected'} |
| **Files** | ${projectStructure.fileCount || '?'} |
| **Commits** | ${gitStats.commits || '?'} |
| **Contributors** | ${gitStats.contributors || '?'} |

## Tech Stack

${stackInfo.full || 'Run /p:analyze to detect stack'}

## Project Structure

${projectStructure.directories?.length ? projectStructure.directories.map(d => `- \`${d}/\``).join('\n') : 'Run /p:analyze to detect structure'}

## Available Agents

${agentExpertise.length ? agentExpertise.map(a => `### ${a.name}
- **Role**: ${a.role}
- **Expertise**: ${a.expertise}
`).join('\n') : 'None. Run /p:sync to generate agents.'}

## Current Focus

${currentTask ? `**Active Task**: ${currentTask}` : 'No active task. Use /p:now to start.'}

## Priority Queue

${nextTasks.length ? nextTasks.map((t, i) => `${i + 1}. ${t}`).join('\n') : 'Empty queue. Use /p:next to add tasks.'}

## Active Features (Roadmap)

${activeFeatures.length ? activeFeatures.map(f => `- [ ] ${f}`).join('\n') : 'No features in progress.'}

## Recent Ideas

${recentIdeas.length ? recentIdeas.map(i => `- ${i}`).join('\n') : 'No recent ideas.'}

## Git Activity

${gitStats.recentCommits?.length ? gitStats.recentCommits.map(c => `- \`${c.hash}\` ${c.message}`).join('\n') : 'No recent commits.'}

---

## Deep Dive (Read When Needed)

For detailed information, read these files:
- \`~/.prjct-cli/projects/${projectId}/agents/*.md\` - Full agent templates with code patterns
- \`~/.prjct-cli/projects/${projectId}/analysis/repo-summary.md\` - Complete technical analysis
- \`~/.prjct-cli/projects/${projectId}/planning/roadmap.md\` - Full feature roadmap
- \`~/.prjct-cli/projects/${projectId}/memory/context.jsonl\` - Decision history
`

  // 11. Write to global storage
  const contextPath = path.join(globalPath, 'CLAUDE.md')
  await fs.writeFile(contextPath, content, 'utf-8')

  return { agents: agentFiles.map(f => f.replace('.md', '')), stack: stackInfo, currentTask }
}

/**
 * Extract FULL stack info from repo-summary
 */
function extractFullStack(summary: string | null): StackInfo {
  if (!summary) return { primary: null, full: null, languages: [], frameworks: [], dependencies: [] }

  const result: StackInfo = { primary: null, full: null, languages: [], frameworks: [], dependencies: [] }

  // Extract languages (e.g., "### JavaScript/TypeScript")
  const langMatch = summary.match(/###\s*(JavaScript|TypeScript|Python|Go|Rust|Ruby|Java|C#|PHP)/i)
  if (langMatch) result.primary = langMatch[1]

  // Extract dependencies
  const depsMatch = summary.match(/\*\*Dependencies\*\*:\s*([^\n]+)/i)
  if (depsMatch) result.dependencies = depsMatch[1].split(',').map(d => d.trim())

  // Extract full stack section (between ## Stack Detected and next ##)
  const stackSection = summary.match(/## Stack Detected\n([\s\S]*?)(?=\n## |$)/i)
  if (stackSection && stackSection[1]) {
    result.full = stackSection[1].trim()
  }

  return result
}

/**
 * Extract project structure from repo-summary
 */
function extractProjectStructure(summary: string | null): ProjectStructure {
  if (!summary) return { fileCount: null, directories: [] }

  const result: ProjectStructure = { fileCount: null, directories: [] }

  // Extract file count
  const fileMatch = summary.match(/\*\*Total Files\*\*:\s*(\d+)/i)
  if (fileMatch) result.fileCount = parseInt(fileMatch[1])

  // Extract directories
  const dirMatch = summary.match(/\*\*Directories\*\*:\s*([^\n]+)/i)
  if (dirMatch) result.directories = dirMatch[1].split(',').map(d => d.trim())

  return result
}

/**
 * Extract git stats from repo-summary
 */
function extractGitStats(summary: string | null): GitStats {
  if (!summary) return { commits: null, contributors: null, recentCommits: [] }

  const result: GitStats = { commits: null, contributors: null, recentCommits: [] }

  // Extract commit count
  const commitMatch = summary.match(/\*\*Total Commits\*\*:\s*(\d+)/i)
  if (commitMatch) result.commits = parseInt(commitMatch[1])

  // Extract contributors
  const contribMatch = summary.match(/\*\*Contributors\*\*:\s*(\d+)/i)
  if (contribMatch) result.contributors = parseInt(contribMatch[1])

  // Extract recent commits
  const recentSection = summary.match(/## Recent Activity[\s\S]*?(?=##|$)/i)
  if (recentSection) {
    const commitLines = recentSection[0].match(/- `([a-f0-9]+)` (.+?) \(/g)
    if (commitLines) {
      result.recentCommits = commitLines.slice(0, 5).map(line => {
        const match = line.match(/- `([a-f0-9]+)` (.+?) \(/)
        return match ? { hash: match[1], message: match[2] } : null
      }).filter((c): c is GitCommit => c !== null)
    }
  }

  return result
}

/**
 * Extract agent expertise from agent files
 */
async function extractAgentExpertise(agentsDir: string, agentFiles: string[]): Promise<AgentExpertise[]> {
  const expertise: AgentExpertise[] = []

  for (const file of agentFiles.slice(0, 6)) { // Max 6 agents to keep context small
    try {
      const content = await fs.readFile(path.join(agentsDir, file), 'utf-8')
      const name = file.replace('.md', '')

      // Extract role
      const roleMatch = content.match(/Role:\s*([^\n]+)/i)
      const role = roleMatch ? roleMatch[1].trim() : 'Specialist'

      // Extract domain or expertise
      const domainMatch = content.match(/domain[:\s]+([^\n]+)/i) ||
                          content.match(/expertise[:\s]+([^\n]+)/i) ||
                          content.match(/owner of the ([^\n.]+)/i)
      const expertiseText = domainMatch ? domainMatch[1].trim() : 'General'

      expertise.push({ name, role, expertise: expertiseText })
    } catch {
      // Skip unreadable agents
    }
  }

  return expertise
}

/**
 * Extract current task from now.md
 */
function extractCurrentTask(now: string | null): string | null {
  if (!now) return null

  const lines = now.split('\n')
  for (const line of lines) {
    const trimmed = line.trim()
    if (trimmed && !trimmed.startsWith('#') && !trimmed.startsWith('<!--') && !trimmed.startsWith('No current')) {
      return trimmed
    }
  }
  return null
}

/**
 * Extract top N tasks from next.md
 */
function extractTopTasks(next: string | null, count: number): string[] {
  if (!next) return []

  return next
    .split('\n')
    .filter(l => l.match(/^[-*\d.]\s/))
    .slice(0, count)
    .map(l => l.replace(/^[-*\d.]\s+/, '').trim())
    .filter(Boolean)
}

/**
 * Extract active features from roadmap.md
 */
function extractActiveFeatures(roadmap: string | null): string[] {
  if (!roadmap) return []

  const features: string[] = []
  const lines = roadmap.split('\n')
  let inActive = false

  for (const line of lines) {
    if (line.includes('Active') || line.includes('In Progress') || line.includes('Current')) {
      inActive = true
      continue
    }
    if (line.startsWith('## ') && inActive) {
      break
    }
    if (inActive && line.match(/^[-*]\s*\[[ x]\]/i)) {
      const feature = line.replace(/^[-*]\s*\[[ x]\]\s*/, '').replace(/\*\*/g, '').trim()
      if (feature) features.push(feature)
    }
  }

  return features.slice(0, 5)
}

/**
 * Extract recent ideas from ideas.md
 */
function extractRecentIdeas(ideas: string | null): string[] {
  if (!ideas) return []

  return ideas
    .split('\n')
    .filter(l => l.match(/^[-*]\s/))
    .slice(0, 3)
    .map(l => l.replace(/^[-*]\s+/, '').trim())
    .filter(Boolean)
}

export { generateLocalContext }
export default { generateLocalContext }
