/**
 * State Storage
 *
 * Manages current task state via storage/state.json
 * Generates context/now.md for Claude
 *
 * Note: Local .prjct-state.md is generated by sync-service which has access
 * to projectPath. This class only has projectId.
 */

import type {
  CurrentTask,
  PreviousTask,
  StateJson,
  Subtask,
  SubtaskCompletionData,
  TaskFeedback,
  TaskHistoryEntry,
  WorkspaceTask,
} from '../schemas/state'
import { StateJsonSchema } from '../schemas/state'
import type { WorkflowCommand } from '../types/workflow'
import { getTimestamp } from '../utils/date-helper'
import { workflowStateMachine } from '../workflow-engine/state-machine'
import type { LifecycleBackend } from './state-storage/lifecycle'
import * as lifecycle from './state-storage/lifecycle'
import type { QueryBackend } from './state-storage/queries'
import * as queries from './state-storage/queries'
import type { SubtaskBackend } from './state-storage/subtasks'
import * as subtasks from './state-storage/subtasks'
import type { WorkspaceBackend } from './state-storage/workspace'
import * as workspace from './state-storage/workspace'
import { StorageManager } from './storage-manager'

class StateStorage extends StorageManager<StateJson> {
  constructor() {
    super('state.json', StateJsonSchema)
  }

  protected getDefault(): StateJson {
    return {
      currentTask: null,
      previousTask: null,
      pausedTasks: [],
      taskHistory: [],
      activeTasks: [],
      lastUpdated: '',
    }
  }

  protected getEventType(action: 'update' | 'create' | 'delete'): string {
    return `state.${action}d`
  }

  // =========== Transition Validation ===========

  /**
   * Validate a state transition through the state machine.
   * Throws if the transition is invalid.
   *
   * When `workspaceId` is provided the lifecycle is evaluated PER workspace
   * (multi-agent parallel mode): a task active in one worktree does not block
   * starting one in another, but a second task in the SAME workspace still
   * gates. Omitting it preserves the legacy singular (currentTask) gate.
   */
  private validateTransition(
    state: StateJson,
    command: WorkflowCommand,
    workspaceId?: string
  ): void {
    const currentState = workflowStateMachine.getCurrentState(state, workspaceId)
    const result = workflowStateMachine.canTransition(currentState, command)
    if (!result.valid) {
      throw new Error(`${result.error}. ${result.suggestion || ''}`.trim())
    }
  }

  // =========== Domain Methods ===========

  /**
   * Get current active task
   */
  async getCurrentTask(projectId: string): Promise<CurrentTask | null> {
    const state = await this.read(projectId)
    return state.currentTask
  }

  /**
   * Get paused tasks (most-recent first). Returns empty array if none.
   */
  async getPausedTasks(projectId: string): Promise<PreviousTask[]> {
    const state = await this.read(projectId)
    return this.getPausedTasksFromState(state)
  }

  /**
   * Start a new task
   */
  async startTask(projectId: string, task: Omit<CurrentTask, 'startedAt'>): Promise<CurrentTask> {
    const state = await this.read(projectId)
    this.validateTransition(state, 'task')

    const currentTask: CurrentTask = {
      ...task,
      startedAt: getTimestamp(),
    }

    await this.update(projectId, (state) => ({
      ...state,
      currentTask,
      lastUpdated: getTimestamp(),
    }))

    // Publish incremental event
    await this.publishEvent(projectId, 'task.started', {
      taskId: currentTask.id,
      description: currentTask.description,
      startedAt: currentTask.startedAt,
      sessionId: currentTask.sessionId,
    })

    return currentTask
  }

  /**
   * Update fields on the current task (partial update)
   */
  async updateCurrentTask(
    projectId: string,
    fields: Partial<CurrentTask>
  ): Promise<CurrentTask | null> {
    const state = await this.read(projectId)
    if (!state.currentTask) return null

    const updated: CurrentTask = { ...state.currentTask, ...fields }

    await this.update(projectId, (s) => ({
      ...s,
      currentTask: updated,
      lastUpdated: getTimestamp(),
    }))

    return updated
  }

  /**
   * Complete current task
   * Creates a TaskHistoryEntry and adds it to taskHistory with FIFO eviction
   * Optionally accepts structured feedback for the task-to-analysis feedback loop (PRJ-272)
   */
  async completeTask(projectId: string, feedback?: TaskFeedback): Promise<CurrentTask | null> {
    const state = await this.read(projectId)
    const completedTask = state.currentTask

    if (!completedTask) {
      return null
    }

    this.validateTransition(state, 'done')

    const completedAt = getTimestamp()

    // Create task history entry for completed task (with optional feedback)
    const historyEntry = this.createTaskHistoryEntry(completedTask, completedAt, feedback)

    // Get existing task history with backward compatibility
    const existingHistory = this.getTaskHistoryFromState(state)

    // Add new entry to beginning, enforce max limit with FIFO eviction
    const taskHistory = [historyEntry, ...existingHistory].slice(0, this.maxTaskHistory)

    await this.update(projectId, (existingState) => ({
      ...existingState,
      currentTask: null,
      previousTask: null,
      taskHistory,
      lastUpdated: completedAt,
    }))

    // Publish incremental event
    await this.publishEvent(projectId, 'task.completed', {
      taskId: completedTask.id,
      description: completedTask.description,
      startedAt: completedTask.startedAt,
      completedAt,
    })

    return completedTask
  }

  /**
   * Create a TaskHistoryEntry from a completed task
   * Optionally includes structured feedback for the feedback loop (PRJ-272)
   */
  private createTaskHistoryEntry(
    task: CurrentTask,
    completedAt: string,
    feedback?: TaskFeedback
  ): TaskHistoryEntry {
    // Extract subtask summaries (only completed subtasks with summaries)
    const subtaskSummaries = (task.subtasks || [])
      .filter((st) => st.status === 'completed' && st.summary)
      .map((st) => st.summary!)

    // Calculate outcome description from subtask summaries
    const outcome =
      subtaskSummaries.length > 0
        ? subtaskSummaries.map((s) => s.title).join(', ')
        : 'Task completed'

    const entry: TaskHistoryEntry = {
      taskId: task.id,
      title: task.parentDescription || task.description,
      classification: task.type || 'improvement',
      startedAt: task.startedAt,
      completedAt,
      subtaskCount: task.subtasks?.length || 0,
      subtaskSummaries,
      outcome,
      branchName: task.branch || 'unknown',
      linearId: task.linearId,
      linearUuid: task.linearUuid,
      prUrl: task.prUrl,
    }

    // Attach feedback if provided (PRJ-272)
    if (feedback) {
      entry.feedback = feedback
    }

    // Carry token usage totals
    if (task.tokensIn) entry.tokensIn = task.tokensIn
    if (task.tokensOut) entry.tokensOut = task.tokensOut

    return entry
  }

  /** Max number of paused tasks (configurable) */
  private maxPausedTasks = 5

  /** Max number of task history entries (configurable) */
  private maxTaskHistory = 20

  /** Staleness threshold in days */
  private stalenessThresholdDays = 30

  // =========== Pause/Resume/Archive (delegated to ./state-storage/lifecycle) ===========

  private lifecycleBackend(): LifecycleBackend {
    return {
      read: this.read.bind(this),
      update: this.update.bind(this),
      publish: this.publishEvent.bind(this),
      validateTransition: this.validateTransition.bind(this),
      getPausedTasksFromState: this.getPausedTasksFromState.bind(this),
      maxPausedTasks: this.maxPausedTasks,
      stalenessThresholdDays: this.stalenessThresholdDays,
    }
  }

  async pauseTask(projectId: string, reason?: string): Promise<PreviousTask | null> {
    return lifecycle.pauseTask(this.lifecycleBackend(), projectId, reason)
  }

  async resumeTask(projectId: string, taskId?: string): Promise<CurrentTask | null> {
    return lifecycle.resumeTask(this.lifecycleBackend(), projectId, taskId)
  }

  /**
   * Get paused tasks from state
   */
  private getPausedTasksFromState(state: StateJson): PreviousTask[] {
    if (Array.isArray(state.pausedTasks) && state.pausedTasks.length > 0) {
      return state.pausedTasks
    }
    // Migrate legacy previousTask into pausedTasks (PRJ-345)
    if (state.previousTask) {
      return [state.previousTask]
    }
    return []
  }

  /**
   * Get task history from state with backward compatibility
   * Ensures taskHistory is always an array (never undefined)
   */
  private getTaskHistoryFromState(state: StateJson): TaskHistoryEntry[] {
    return state.taskHistory || []
  }

  async getStalePausedTasks(projectId: string): Promise<PreviousTask[]> {
    return lifecycle.getStalePausedTasks(this.lifecycleBackend(), projectId)
  }

  async archiveStalePausedTasks(projectId: string): Promise<PreviousTask[]> {
    return lifecycle.archiveStalePausedTasks(this.lifecycleBackend(), projectId)
  }

  // =========== Query helpers (delegated to ./state-storage/queries) ===========

  private queryBackend(): QueryBackend {
    return {
      read: this.read.bind(this),
      update: this.update.bind(this),
      getPausedTasksFromState: this.getPausedTasksFromState.bind(this),
      getTaskHistoryFromState: this.getTaskHistoryFromState.bind(this),
    }
  }

  async clearTask(projectId: string): Promise<void> {
    return queries.clearTask(this.queryBackend(), projectId)
  }

  async hasTask(projectId: string): Promise<boolean> {
    return queries.hasTask(this.queryBackend(), projectId)
  }

  async getPausedTask(projectId: string): Promise<PreviousTask | null> {
    return queries.getPausedTask(this.queryBackend(), projectId)
  }

  async getAllPausedTasks(projectId: string): Promise<PreviousTask[]> {
    return queries.getAllPausedTasks(this.queryBackend(), projectId)
  }

  async getTaskHistory(projectId: string): Promise<TaskHistoryEntry[]> {
    return queries.getTaskHistory(this.queryBackend(), projectId)
  }

  async getMostRecentTask(projectId: string): Promise<TaskHistoryEntry | null> {
    return queries.getMostRecentTask(this.queryBackend(), projectId)
  }

  async getTaskHistoryByType(
    projectId: string,
    classification: TaskHistoryEntry['classification']
  ): Promise<TaskHistoryEntry[]> {
    return queries.getTaskHistoryByType(this.queryBackend(), projectId, classification)
  }

  async getAggregatedFeedback(projectId: string) {
    return queries.getAggregatedFeedback(this.queryBackend(), projectId)
  }

  // =========== Workspace + Tokens (delegated to ./state-storage/workspace) ===========

  private workspaceBackend(): WorkspaceBackend {
    return {
      read: this.read.bind(this),
      update: this.update.bind(this),
      publish: this.publishEvent.bind(this),
      createTaskHistoryEntry: this.createTaskHistoryEntry.bind(this),
      getTaskHistoryFromState: this.getTaskHistoryFromState.bind(this),
      maxTaskHistory: this.maxTaskHistory,
    }
  }

  async startTaskInWorkspace(
    projectId: string,
    task: Omit<WorkspaceTask, 'startedAt'>,
    workspaceId: string
  ): Promise<WorkspaceTask> {
    // Per-workspace gate: a task already active in THIS workspace blocks a new
    // one (same as the singular path), but other workspaces are unaffected.
    const state = await this.read(projectId)
    this.validateTransition(state, 'task', workspaceId)
    return workspace.startTaskInWorkspace(this.workspaceBackend(), projectId, task, workspaceId)
  }

  async getCurrentTaskForWorkspace(
    projectId: string,
    workspaceId: string
  ): Promise<WorkspaceTask | null> {
    return workspace.getCurrentTaskForWorkspace(this.workspaceBackend(), projectId, workspaceId)
  }

  async completeTaskInWorkspace(
    projectId: string,
    workspaceId: string,
    feedback?: TaskFeedback
  ): Promise<WorkspaceTask | null> {
    return workspace.completeTaskInWorkspace(
      this.workspaceBackend(),
      projectId,
      workspaceId,
      feedback
    )
  }

  async getActiveTasks(projectId: string): Promise<WorkspaceTask[]> {
    return workspace.getActiveTasks(this.workspaceBackend(), projectId)
  }

  async getActiveTaskCount(projectId: string): Promise<number> {
    return workspace.getActiveTaskCount(this.workspaceBackend(), projectId)
  }

  async updateWorkspaceTask(
    projectId: string,
    workspaceId: string,
    fields: Partial<WorkspaceTask>
  ): Promise<WorkspaceTask | null> {
    return workspace.updateWorkspaceTask(this.workspaceBackend(), projectId, workspaceId, fields)
  }

  async addTokens(
    projectId: string,
    tokensIn: number,
    tokensOut: number,
    workspaceId?: string
  ): Promise<{ tokensIn: number; tokensOut: number } | null> {
    return workspace.addTokens(this.workspaceBackend(), projectId, tokensIn, tokensOut, workspaceId)
  }

  // =========== Subtask Methods (delegated to ./state-storage/subtasks) ===========

  private subtaskBackend(): SubtaskBackend {
    return {
      read: this.read.bind(this),
      update: this.update.bind(this),
      publish: this.publishEvent.bind(this),
    }
  }

  async createSubtasks(
    projectId: string,
    items: Omit<Subtask, 'status' | 'startedAt' | 'completedAt' | 'output' | 'summary'>[]
  ): Promise<void> {
    return subtasks.createSubtasks(this.subtaskBackend(), projectId, items)
  }

  async completeSubtask(
    projectId: string,
    completionData: SubtaskCompletionData
  ): Promise<Subtask | null> {
    return subtasks.completeSubtask(this.subtaskBackend(), projectId, completionData)
  }

  async getCurrentSubtask(projectId: string): Promise<Subtask | null> {
    return subtasks.getCurrentSubtask(this.subtaskBackend(), projectId)
  }

  async getNextSubtask(projectId: string): Promise<Subtask | null> {
    return subtasks.getNextSubtask(this.subtaskBackend(), projectId)
  }

  async getPreviousSubtask(projectId: string): Promise<Subtask | null> {
    return subtasks.getPreviousSubtask(this.subtaskBackend(), projectId)
  }

  async getPreviousHandoff(projectId: string) {
    return subtasks.getPreviousHandoff(this.subtaskBackend(), projectId)
  }

  async getSubtasks(projectId: string): Promise<Subtask[]> {
    return subtasks.getSubtasks(this.subtaskBackend(), projectId)
  }

  async getSubtaskProgress(projectId: string) {
    return subtasks.getSubtaskProgress(this.subtaskBackend(), projectId)
  }

  async hasSubtasks(projectId: string): Promise<boolean> {
    return subtasks.hasSubtasks(this.subtaskBackend(), projectId)
  }

  async areAllSubtasksComplete(projectId: string): Promise<boolean> {
    return subtasks.areAllSubtasksComplete(this.subtaskBackend(), projectId)
  }

  async failSubtask(projectId: string, error: string): Promise<Subtask | null> {
    return subtasks.failSubtask(this.subtaskBackend(), projectId, error)
  }

  async skipSubtask(projectId: string, reason: string): Promise<Subtask | null> {
    return subtasks.skipSubtask(this.subtaskBackend(), projectId, reason)
  }

  async blockSubtask(projectId: string, blocker: string): Promise<Subtask | null> {
    return subtasks.blockSubtask(this.subtaskBackend(), projectId, blocker)
  }
}

export const stateStorage = new StateStorage()
