/**
 * Agent Router
 * Orchestrates agent loading and context building for Claude delegation.
 *
 * Loads agents from global storage:
 * ~/.prjct-cli/projects/{id}/agents/
 *
 * Agents are dynamically generated by /p:sync based on project tech stack.
 *
 * @module agentic/agent-router
 * @version 4.0.0
 */

import fs from 'node:fs/promises'
import path from 'node:path'
import configManager from '../infrastructure/config-manager'
import pathManager from '../infrastructure/path-manager'
import type { Agent, AssignmentContext } from '../types/agents'
import { getErrorMessage, isNotFoundError } from '../types/fs'

// Re-export types for convenience
export type { Agent, AssignmentContext } from '../types/agents'

/**
 * Routes tasks to specialized agents based on Claude's decisions.
 * Handles agent loading, context building, and usage logging.
 */
class AgentRouter {
  projectId: string | null = null
  projectPath: string | null = null
  agentsPath: string | null = null

  /**
   * Initialize router with project context
   */
  async initialize(projectPath: string): Promise<void> {
    this.projectId = await configManager.getProjectId(projectPath)
    this.projectPath = projectPath
    this.agentsPath = pathManager.getFilePath(this.projectId!, 'agents', '')
  }

  /**
   * Load all available agents from global storage
   */
  async loadAvailableAgents(): Promise<Agent[]> {
    if (!this.agentsPath) return []

    try {
      const files = await fs.readdir(this.agentsPath)
      const agents: Agent[] = []

      for (const file of files) {
        if (file.endsWith('.md')) {
          const name = file.replace('.md', '')
          const content = await fs.readFile(path.join(this.agentsPath, file), 'utf-8')
          agents.push({ name, content })
        }
      }

      return agents
    } catch (error) {
      // Agents directory doesn't exist yet - expected for new projects
      if (!isNotFoundError(error)) {
        console.error(`Agent loading error: ${getErrorMessage(error)}`)
      }
      return []
    }
  }

  /**
   * Get list of available agent names
   */
  async getAgentNames(): Promise<string[]> {
    const agents = await this.loadAvailableAgents()
    return agents.map((a) => a.name)
  }

  /**
   * Load a specific agent by name from global storage
   */
  async loadAgent(name: string): Promise<Agent | null> {
    if (!this.agentsPath) return null

    try {
      const filePath = path.join(this.agentsPath, `${name}.md`)
      const content = await fs.readFile(filePath, 'utf-8')
      return { name, content }
    } catch (error) {
      // Agent file doesn't exist - expected
      if (!isNotFoundError(error)) {
        console.error(`Agent load error: ${getErrorMessage(error)}`)
      }
      return null
    }
  }

  /**
   * Build context for Claude to decide agent assignment
   */
  async buildAssignmentContext(
    task: string | { description?: string },
    projectPath: string
  ): Promise<AssignmentContext> {
    const agents = await this.getAgentNames()

    return {
      task: typeof task === 'string' ? task : task.description || '',
      availableAgents: agents,
      projectPath,
      projectId: this.projectId,
      // Claude reads this and decides via template
      _template: 'templates/agent-assignment.md',
    }
  }

  /**
   * Log agent usage to JSONL file
   */
  async logUsage(
    task: string | { description?: string },
    agent: string | { name?: string },
    _projectPath: string
  ): Promise<void> {
    try {
      const logPath = path.join(
        process.env.HOME || '',
        '.prjct-cli',
        'projects',
        this.projectId || '',
        'agent-usage.jsonl'
      )

      const entry = `${JSON.stringify({
        timestamp: new Date().toISOString(),
        task: typeof task === 'string' ? task : task.description,
        agent: typeof agent === 'string' ? agent : agent.name,
        projectId: this.projectId,
      })}\n`

      await fs.appendFile(logPath, entry)
    } catch (error) {
      // Non-critical - log unexpected errors but don't fail
      if (!isNotFoundError(error)) {
        console.error(`Agent usage log error: ${getErrorMessage(error)}`)
      }
    }
  }
}

export default AgentRouter
