#!/usr/bin/env bun
/**
 * REAL OUTPUT — runs the actual sync pipeline on THIS project
 * and copies every generated artifact to output/ (project root)
 *
 * Dumps:
 * - Claude skills (15 SKILL.md files)
 * - Global CLAUDE.md, GEMINI.md
 * - Codex skill (single SKILL.md)
 * - Antigravity skill (single SKILL.md)
 * - Sync result summary
 *
 * Run: bun run core/__tests__/verify-llm-over-heuristic.ts
 */

import fs from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import { syncService } from '../services/sync-service'

const PROJECT_PATH = process.cwd()
const OUTPUT_DIR = path.join(PROJECT_PATH, 'output')
const HOME = os.homedir()

async function copyIfExists(src: string, dest: string): Promise<boolean> {
  try {
    await fs.mkdir(path.dirname(dest), { recursive: true })
    await fs.copyFile(src, dest)
    return true
  } catch {
    return false
  }
}

async function copyDirIfExists(src: string, dest: string): Promise<number> {
  let count = 0
  try {
    const entries = await fs.readdir(src, { withFileTypes: true })
    for (const entry of entries) {
      const srcPath = path.join(src, entry.name)
      const destPath = path.join(dest, entry.name)
      if (entry.isDirectory()) {
        count += await copyDirIfExists(srcPath, destPath)
      } else {
        await fs.mkdir(path.dirname(destPath), { recursive: true })
        await fs.copyFile(srcPath, destPath)
        count++
      }
    }
  } catch {
    // directory doesn't exist
  }
  return count
}

async function readIfExists(filePath: string): Promise<string | null> {
  try {
    return await fs.readFile(filePath, 'utf-8')
  } catch {
    return null
  }
}

async function main() {
  console.log('Running REAL sync on', PROJECT_PATH, '...\n')

  const result = await syncService.sync(PROJECT_PATH)

  if (!result.success) {
    console.error('Sync failed:', result.error)
    process.exit(1)
  }

  // Clean output dir
  await fs.rm(OUTPUT_DIR, { recursive: true, force: true })
  await fs.mkdir(OUTPUT_DIR, { recursive: true })

  // ═══════════════════════════════════════════════════════════════════════
  // 1. CLAUDE — Skills (generated by sync)
  // ═══════════════════════════════════════════════════════════════════════
  const skillsOutputDir = path.join(OUTPUT_DIR, 'claude', 'skills')
  if (result.generatedSkills) {
    for (const skill of result.generatedSkills.generated) {
      const destDir = path.join(skillsOutputDir, skill.name)
      await fs.mkdir(destDir, { recursive: true })
      await fs.copyFile(skill.path, path.join(destDir, 'SKILL.md'))
    }
  }

  // ═══════════════════════════════════════════════════════════════════════
  // 2. CLAUDE — Global CLAUDE.md
  // ═══════════════════════════════════════════════════════════════════════
  await copyIfExists(
    path.join(HOME, '.claude', 'CLAUDE.md'),
    path.join(OUTPUT_DIR, 'claude', 'CLAUDE.md')
  )

  // ═══════════════════════════════════════════════════════════════════════
  // 3. GEMINI — Global GEMINI.md
  // ═══════════════════════════════════════════════════════════════════════
  await copyIfExists(
    path.join(HOME, '.gemini', 'GEMINI.md'),
    path.join(OUTPUT_DIR, 'gemini', 'GEMINI.md')
  )

  // Gemini skills (same dir structure as Claude if they exist)
  await copyDirIfExists(
    path.join(HOME, '.gemini', 'skills'),
    path.join(OUTPUT_DIR, 'gemini', 'skills')
  )

  // ═══════════════════════════════════════════════════════════════════════
  // 4. CODEX — Single SKILL.md + instructions.md
  // ═══════════════════════════════════════════════════════════════════════
  await copyIfExists(
    path.join(HOME, '.codex', 'skills', 'prjct', 'SKILL.md'),
    path.join(OUTPUT_DIR, 'codex', 'skills', 'prjct', 'SKILL.md')
  )
  await copyIfExists(
    path.join(HOME, '.codex', 'instructions.md'),
    path.join(OUTPUT_DIR, 'codex', 'instructions.md')
  )

  // ═══════════════════════════════════════════════════════════════════════
  // 5. ANTIGRAVITY — Single SKILL.md
  // ═══════════════════════════════════════════════════════════════════════
  // global_skills (provider config says this)
  await copyDirIfExists(
    path.join(HOME, '.gemini', 'antigravity', 'skills'),
    path.join(OUTPUT_DIR, 'antigravity', 'skills')
  )
  await copyDirIfExists(
    path.join(HOME, '.gemini', 'antigravity', 'global_skills'),
    path.join(OUTPUT_DIR, 'antigravity', 'global_skills')
  )

  // ═══════════════════════════════════════════════════════════════════════
  // 6. CURSOR — Project-level (.cursor/)
  // ═══════════════════════════════════════════════════════════════════════
  await copyDirIfExists(path.join(PROJECT_PATH, '.cursor'), path.join(OUTPUT_DIR, 'cursor'))

  // ═══════════════════════════════════════════════════════════════════════
  // 7. WINDSURF — Project-level (.windsurf/)
  // ═══════════════════════════════════════════════════════════════════════
  await copyDirIfExists(path.join(PROJECT_PATH, '.windsurf'), path.join(OUTPUT_DIR, 'windsurf'))

  // ═══════════════════════════════════════════════════════════════════════
  // CONSOLE OUTPUT
  // ═══════════════════════════════════════════════════════════════════════
  const lines: string[] = []
  const w = (s: string) => lines.push(s)

  w('=== SYNC RESULT ===')
  w(`projectId: ${result.projectId}`)
  w(`cliVersion: ${result.cliVersion}`)
  w('')
  w('=== STATS ===')
  w(`name:        ${result.stats.name}`)
  w(`version:     ${result.stats.version}`)
  w(`ecosystem:   ${result.stats.ecosystem}`)
  w(`languages:   ${JSON.stringify(result.stats.languages)}`)
  w(`frameworks:  ${JSON.stringify(result.stats.frameworks)}`)
  w(`fileCount:   ${result.stats.fileCount}`)
  w(`projectType: ${result.stats.projectType}`)
  w('')
  w('=== COMMANDS ===')
  w(`install: ${result.commands.install}`)
  w(`test:    ${result.commands.test}`)
  w(`build:   ${result.commands.build}`)
  w(`dev:     ${result.commands.dev}`)
  w(`lint:    ${result.commands.lint}`)
  w(`format:  ${result.commands.format}`)
  w('')
  w('=== STACK ===')
  w(`hasFrontend: ${result.stack.hasFrontend}`)
  w(`hasBackend:  ${result.stack.hasBackend}`)
  w(`hasDatabase: ${result.stack.hasDatabase}`)
  w(`hasDocker:   ${result.stack.hasDocker}`)
  w(`hasTesting:  ${result.stack.hasTesting}`)
  w(`frameworks:  ${JSON.stringify(result.stack.frameworks)}`)
  w('')
  w('=== GENERATED SKILLS (Claude) ===')
  if (result.generatedSkills) {
    w(
      `generated (${result.generatedSkills.generated.length}): ${result.generatedSkills.generated.map((s) => s.name).join(', ')}`
    )
    w(
      `skipped:   ${result.generatedSkills.skipped.map((s) => `${s.name} (${s.reason})`).join(', ') || 'none'}`
    )
  }
  w('')
  w('=== ANALYSIS SUMMARY ===')
  w(`patterns:             ${result.analysisSummary?.patterns ?? 'n/a'}`)
  w(`antiPatterns:          ${result.analysisSummary?.antiPatterns ?? 'n/a'}`)
  w(`criticalAntiPatterns:  ${result.analysisSummary?.criticalAntiPatterns ?? 'n/a'}`)

  // ── Provider global configs ──────────────────────────────────────────
  w('')
  w('═══════════════════════════════════════════════════════════')
  w('  PROVIDER ARTIFACTS')
  w('═══════════════════════════════════════════════════════════')

  // Claude CLAUDE.md
  const claudeMd = await readIfExists(path.join(HOME, '.claude', 'CLAUDE.md'))
  w('')
  w('── CLAUDE.md ──')
  if (claudeMd) {
    // Extract just the prjct section
    const start = claudeMd.indexOf('<!-- prjct:start')
    const end = claudeMd.indexOf('<!-- prjct:end')
    if (start >= 0 && end >= 0) {
      w(claudeMd.substring(start, end + claudeMd.substring(end).indexOf('\n') + 1).trim())
    } else {
      w(claudeMd.substring(0, 500))
    }
  } else {
    w('  (not found)')
  }

  // Gemini GEMINI.md
  const geminiMd = await readIfExists(path.join(HOME, '.gemini', 'GEMINI.md'))
  w('')
  w('── GEMINI.md ──')
  if (geminiMd) {
    const start = geminiMd.indexOf('<!-- prjct:start')
    const end = geminiMd.indexOf('<!-- prjct:end')
    if (start >= 0 && end >= 0) {
      w(geminiMd.substring(start, end + geminiMd.substring(end).indexOf('\n') + 1).trim())
    } else {
      w(geminiMd.substring(0, 500))
    }
  } else {
    w('  (not found)')
  }

  // Codex SKILL.md
  const codexSkill = await readIfExists(path.join(HOME, '.codex', 'skills', 'prjct', 'SKILL.md'))
  w('')
  w('── CODEX skill ──')
  if (codexSkill) {
    w(codexSkill.trim())
  } else {
    w('  (not found)')
  }

  // Codex instructions.md
  const codexInstructions = await readIfExists(path.join(HOME, '.codex', 'instructions.md'))
  w('')
  w('── CODEX instructions.md ──')
  if (codexInstructions) {
    w(codexInstructions.substring(0, 500).trim())
    if (codexInstructions.length > 500) w('  ... (truncated)')
  } else {
    w('  (not found)')
  }

  // Antigravity skill
  for (const subdir of ['skills', 'global_skills']) {
    const agSkill = await readIfExists(
      path.join(HOME, '.gemini', 'antigravity', subdir, 'prjct', 'SKILL.md')
    )
    if (agSkill) {
      w('')
      w(`── ANTIGRAVITY ${subdir}/prjct/SKILL.md ──`)
      w(agSkill.trim())
    }
  }

  // Cursor project-level
  const cursorRouter = await readIfExists(path.join(PROJECT_PATH, '.cursor', 'rules', 'prjct.mdc'))
  w('')
  w('── CURSOR .cursor/rules/prjct.mdc ──')
  w(cursorRouter ? cursorRouter.substring(0, 500).trim() : '  (not found)')

  // Windsurf project-level
  const windsurfRouter = await readIfExists(
    path.join(PROJECT_PATH, '.windsurf', 'rules', 'prjct.md')
  )
  w('')
  w('── WINDSURF .windsurf/rules/prjct.md ──')
  w(windsurfRouter ? windsurfRouter.substring(0, 500).trim() : '  (not found)')

  // ── prjct-context SKILL.md content ───────────────────────────────────
  w('')
  w('═══════════════════════════════════════════════════════════')
  w('  prjct-context SKILL.md (full content)')
  w('═══════════════════════════════════════════════════════════')
  const contextSkill = result.generatedSkills?.generated.find((s) => s.name === 'prjct-context')
  if (contextSkill) {
    const content = await readIfExists(contextSkill.path)
    w(content?.trim() ?? '  (empty)')
  } else {
    w('  (not generated)')
  }

  await fs.writeFile(path.join(OUTPUT_DIR, 'sync-result.txt'), `${lines.join('\n')}\n`)

  console.log(lines.join('\n'))
  console.log('')
  console.log('=== FILES IN output/ ===')
  const walk = async (dir: string, prefix = '') => {
    const entries = await fs.readdir(dir, { withFileTypes: true })
    for (const e of entries.sort((a, b) => a.name.localeCompare(b.name))) {
      const rel = prefix ? `${prefix}/${e.name}` : e.name
      if (e.isDirectory()) {
        await walk(path.join(dir, e.name), rel)
      } else {
        const stat = await fs.stat(path.join(dir, e.name))
        console.log(`  ${rel}  (${stat.size} bytes)`)
      }
    }
  }
  await walk(OUTPUT_DIR)
}

main().catch((err) => {
  console.error('Crashed:', err)
  process.exit(1)
})
