/**
 * Command Data - Static command definitions and categories
 *
 * Single source of truth for all command metadata.
 * Used by registry for introspection and help display.
 */

import type { CategoryInfo, CommandMeta } from '../types'

// Category definitions
export const CATEGORIES: Record<string, CategoryInfo> = {
  core: {
    title: 'Core Workflow',
    description: '13 essential commands for daily development workflow',
    order: 1,
  },
  optional: {
    title: 'Optional Commands',
    description: 'Advanced features for specialized workflows',
    order: 2,
  },
  setup: {
    title: 'Setup',
    description: 'Installation and configuration (not for daily use)',
    order: 3,
  },
}

// All command definitions
export const COMMANDS: CommandMeta[] = [
  // ===== CORE COMMANDS =====
  {
    name: 'init',
    group: 'core',
    description: 'Deep project analysis and initialization',
    usage: { claude: '/p:init "[idea]"', terminal: 'prjct init "[idea]"' },
    params: '[idea]',
    implemented: true,
    hasTemplate: true,
    requiresProject: false,
    features: [
      'Architect mode for blank projects',
      'Auto tech stack recommendation',
      'Analyzes existing codebases',
    ],
  },
  {
    name: 'idea',
    group: 'core',
    description: 'Transform ideas into complete technical architectures',
    usage: { claude: '/p:idea "build a CRM"', terminal: 'prjct idea "build a CRM"' },
    params: '<description>',
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    features: ['Simple ideas -> Quick capture', 'Complex ideas -> Full architecture'],
  },
  {
    name: 'task',
    group: 'core',
    description: 'Start task with agentic classification and 7-phase workflow',
    usage: { claude: '/p:task "<description>"', terminal: 'prjct task "<description>"' },
    params: '<description>',
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    features: [
      'Agentic type classification',
      '7-phase workflow',
      'Git branch management',
      'Task breakdown',
    ],
  },
  {
    name: 'spec',
    group: 'core',
    description: 'Create detailed specifications for complex features',
    usage: { claude: '/p:spec "Dark Mode"', terminal: 'prjct spec "Dark Mode"' },
    params: '[feature]',
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
  },
  {
    name: 'pause',
    group: 'core',
    description: 'Pause active task to handle interruption',
    usage: { claude: '/p:pause ["reason"]', terminal: 'prjct pause ["reason"]' },
    params: '[reason]',
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    blockingRules: { check: 'Active task exists', message: 'No active task to pause' },
  },
  {
    name: 'resume',
    group: 'core',
    description: 'Resume paused task or recover abandoned session',
    usage: { claude: '/p:resume', terminal: 'prjct resume' },
    params: '[task_id]',
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
  },
  {
    name: 'next',
    group: 'core',
    description: 'Show priority queue or roadmap view',
    usage: { claude: '/p:next', terminal: 'prjct next' },
    params: '[roadmap]',
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
  },
  {
    name: 'done',
    group: 'core',
    description: 'Mark current task as complete',
    usage: { claude: '/p:done', terminal: 'prjct done' },
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
  },
  {
    name: 'ship',
    group: 'core',
    description: 'Commit, push, and celebrate shipped feature',
    usage: { claude: '/p:ship "feature"', terminal: 'prjct ship "feature"' },
    params: '<feature>',
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
  },
  {
    name: 'bug',
    group: 'core',
    description: 'Report and track bugs with priority',
    usage: { claude: '/p:bug "description"', terminal: 'prjct bug "description"' },
    params: '<description>',
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
  },
  {
    name: 'dash',
    group: 'core',
    description: 'Unified dashboard - status, progress, and roadmap',
    usage: { claude: '/p:dash [view]', terminal: 'prjct dash [view]' },
    params: '[week|month|roadmap|compact]',
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
  },
  {
    name: 'stats',
    group: 'core',
    description: 'Value dashboard - token savings, performance, and impact',
    usage: { claude: '/p:stats', terminal: 'prjct stats' },
    params: '[--json] [--export]',
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    features: ['Token savings tracking', 'Compression metrics', 'Cost estimates', '30-day trends'],
  },
  {
    name: 'sync',
    group: 'core',
    description: 'Sync project state and update workflow agents',
    usage: { claude: '/p:sync', terminal: 'prjct sync [--package=<name>]' },
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    features: [
      'Monorepo support: --package=<name> for single package sync',
      'Nested PRJCT.md inheritance',
      'Per-package CLAUDE.md generation',
    ],
  },
  {
    name: 'perf',
    group: 'core',
    description: 'Performance dashboard - startup, memory, context, and handoff metrics',
    usage: { claude: '/p:perf', terminal: 'prjct perf [days]' },
    params: '[days]',
    implemented: true,
    hasTemplate: false,
    requiresProject: true,
    features: [
      'Startup time tracking',
      'Memory usage snapshots',
      'Context correctness rate',
      'Subtask handoff rate',
      'Command duration breakdown',
    ],
  },
  {
    name: 'suggest',
    group: 'core',
    description: 'Smart recommendations based on project state',
    usage: { claude: '/p:suggest', terminal: 'prjct suggest' },
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
  },
  {
    name: 'status',
    group: 'core',
    description: 'Check if CLAUDE.md context is stale and needs resync',
    usage: { claude: '/p:status', terminal: 'prjct status' },
    params: '[--json]',
    implemented: true,
    hasTemplate: false,
    requiresProject: true,
    features: [
      'Compares current HEAD with last sync commit',
      'Counts commits and days since sync',
      'Detects significant file changes',
      'Configurable staleness thresholds',
    ],
  },
  {
    name: 'help',
    group: 'core',
    description: 'Contextual help and guidance',
    usage: { claude: '/p:help [topic]', terminal: 'prjct help [topic]' },
    params: '[topic]',
    implemented: true,
    hasTemplate: true,
    requiresProject: false,
  },

  // ===== OPTIONAL COMMANDS =====
  {
    name: 'design',
    group: 'optional',
    description: 'Design system architecture, APIs, and components',
    usage: { claude: '/p:design [target]', terminal: 'prjct design [target]' },
    params: '[target] --type architecture|api|component',
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    isOptional: true,
  },
  {
    name: 'cleanup',
    group: 'optional',
    description: 'Clean up temp files and old entries',
    usage: { claude: '/p:cleanup', terminal: 'prjct cleanup' },
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    isOptional: true,
  },
  {
    name: 'analyze',
    group: 'optional',
    description: 'Analyze repository and sync tasks',
    usage: { claude: '/p:analyze', terminal: 'prjct analyze' },
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    isOptional: true,
  },
  {
    name: 'undo',
    group: 'optional',
    description: 'Revert to previous snapshot',
    usage: { claude: '/p:undo', terminal: 'prjct undo' },
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    isOptional: true,
    features: ['Git-based snapshots', 'Preserves redo history'],
  },
  {
    name: 'redo',
    group: 'optional',
    description: 'Redo previously undone changes',
    usage: { claude: '/p:redo', terminal: 'prjct redo' },
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    isOptional: true,
  },
  {
    name: 'history',
    group: 'optional',
    description: 'View snapshot history',
    usage: { claude: '/p:history', terminal: 'prjct history' },
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    isOptional: true,
  },
  {
    name: 'recover',
    group: 'optional',
    description: 'Recover abandoned session with context',
    usage: { claude: '/p:recover', terminal: 'prjct recover' },
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    isOptional: true,
  },
  {
    name: 'git',
    group: 'optional',
    description: 'Smart git operations with context',
    usage: { claude: '/p:git [op]', terminal: 'prjct git [op]' },
    params: '[operation]',
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    isOptional: true,
  },
  {
    name: 'test',
    group: 'optional',
    description: 'Run tests with auto-fix',
    usage: { claude: '/p:test', terminal: 'prjct test' },
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    isOptional: true,
  },
  {
    name: 'workflow',
    group: 'optional',
    description: 'Configure workflow hooks via natural language',
    usage: { claude: '/p:workflow ["config"]', terminal: 'prjct workflow ["config"]' },
    params: '["natural language config"]',
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    isOptional: true,
    features: [
      'Natural language configuration',
      'Before/after hooks for task, done, ship, sync',
      'Permanent, session, or one-time preferences',
    ],
  },

  // ===== SETUP COMMANDS =====
  {
    name: 'start',
    group: 'setup',
    description: 'First-time setup (install commands to editors)',
    usage: { claude: null, terminal: 'prjct start' },
    implemented: true,
    hasTemplate: false,
    requiresProject: false,
  },
  {
    name: 'setup',
    group: 'setup',
    description: 'Reconfigure editor installations',
    usage: { claude: '/p:setup', terminal: 'prjct setup' },
    params: '[--force] [--editor <name>]',
    implemented: true,
    hasTemplate: true,
    requiresProject: false,
  },
  {
    name: 'migrate',
    group: 'setup',
    description: 'Migrate project to UUID format + sync',
    usage: { claude: '/p:migrate', terminal: null },
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
  },
  {
    name: 'auth',
    group: 'setup',
    description: 'Manage cloud authentication',
    usage: { claude: '/p:auth [action]', terminal: 'prjct auth [action]' },
    params: '[login|logout|status]',
    implemented: true,
    hasTemplate: true,
    requiresProject: false,
  },
  {
    name: 'context',
    group: 'setup',
    description: 'Smart context filtering tools for AI agents',
    usage: { claude: null, terminal: 'prjct context <tool> [args]' },
    params: '<tool> [args]',
    implemented: true,
    hasTemplate: false,
    requiresProject: true,
    features: [
      'files - Find relevant files for a task',
      'signatures - Extract code structure (~90% compression)',
      'imports - Analyze dependency graphs',
      'recent - Find hot files from git history',
      'summary - Intelligent file summarization',
    ],
  },
  {
    name: 'uninstall',
    group: 'setup',
    description: 'Complete system removal of prjct',
    usage: { claude: null, terminal: 'prjct uninstall' },
    params: '[--force] [--backup] [--dry-run]',
    implemented: true,
    hasTemplate: false,
    requiresProject: false,
    features: [
      'Removes ~/.prjct-cli/ data',
      'Cleans CLAUDE.md prjct section',
      'Uninstalls Homebrew/npm packages',
      'Backup option before deletion',
    ],
  },
]
