/**
 * Command Data - Static command definitions and categories
 *
 * Single source of truth for all command metadata.
 * Used by registry for introspection and help display.
 */

import type { CommandMeta, CategoryInfo } from '../types'

// Category definitions
export const CATEGORIES: Record<string, CategoryInfo> = {
  core: {
    title: 'Core Workflow',
    description: '13 essential commands for daily development workflow',
    order: 1,
  },
  optional: {
    title: 'Optional Commands',
    description: 'Advanced features for specialized workflows',
    order: 2,
  },
  setup: {
    title: 'Setup',
    description: 'Installation and configuration (not for daily use)',
    order: 3,
  },
}

// All command definitions
export const COMMANDS: CommandMeta[] = [
  // ===== CORE COMMANDS =====
  {
    name: 'init',
    group: 'core',
    description: 'Deep project analysis and initialization',
    usage: { claude: '/p:init "[idea]"', terminal: 'prjct init "[idea]"' },
    params: '[idea]',
    implemented: true,
    hasTemplate: true,
    requiresProject: false,
    features: ['Architect mode for blank projects', 'Auto tech stack recommendation', 'Analyzes existing codebases'],
  },
  {
    name: 'idea',
    group: 'core',
    description: 'Transform ideas into complete technical architectures',
    usage: { claude: '/p:idea "build a CRM"', terminal: 'prjct idea "build a CRM"' },
    params: '<description>',
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    features: ['Simple ideas -> Quick capture', 'Complex ideas -> Full architecture'],
  },
  {
    name: 'task',
    group: 'core',
    description: 'Start task with agentic classification and 7-phase workflow',
    usage: { claude: '/p:task "<description>"', terminal: 'prjct task "<description>"' },
    params: '<description>',
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    features: ['Agentic type classification', '7-phase workflow', 'Git branch management', 'Task breakdown'],
  },
  {
    name: 'feature',
    group: 'core',
    description: 'DEPRECATED - Use /p:task instead',
    usage: { claude: '/p:task "<description>"', terminal: 'prjct task "<description>"' },
    params: '<description>',
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    deprecated: true,
  },
  {
    name: 'spec',
    group: 'core',
    description: 'Create detailed specifications for complex features',
    usage: { claude: '/p:spec "Dark Mode"', terminal: 'prjct spec "Dark Mode"' },
    params: '[feature]',
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
  },
  {
    name: 'now',
    group: 'core',
    description: 'DEPRECATED - Use /p:task instead',
    usage: { claude: '/p:task "<description>"', terminal: 'prjct task "<description>"' },
    params: '[task]',
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    deprecated: true,
  },
  {
    name: 'work',
    group: 'core',
    description: 'DEPRECATED - Use /p:task instead',
    usage: { claude: '/p:task "<description>"', terminal: 'prjct task "<description>"' },
    params: '[task]',
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    deprecated: true,
  },
  {
    name: 'pause',
    group: 'core',
    description: 'Pause active task to handle interruption',
    usage: { claude: '/p:pause ["reason"]', terminal: 'prjct pause ["reason"]' },
    params: '[reason]',
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    blockingRules: { check: 'Active task exists', message: 'No active task to pause' },
  },
  {
    name: 'resume',
    group: 'core',
    description: 'Resume paused task or recover abandoned session',
    usage: { claude: '/p:resume', terminal: 'prjct resume' },
    params: '[task_id]',
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
  },
  {
    name: 'next',
    group: 'core',
    description: 'Show priority queue or roadmap view',
    usage: { claude: '/p:next', terminal: 'prjct next' },
    params: '[roadmap]',
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
  },
  {
    name: 'done',
    group: 'core',
    description: 'Mark current task as complete',
    usage: { claude: '/p:done', terminal: 'prjct done' },
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
  },
  {
    name: 'ship',
    group: 'core',
    description: 'Commit, push, and celebrate shipped feature',
    usage: { claude: '/p:ship "feature"', terminal: 'prjct ship "feature"' },
    params: '<feature>',
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
  },
  {
    name: 'bug',
    group: 'core',
    description: 'Report and track bugs with priority',
    usage: { claude: '/p:bug "description"', terminal: 'prjct bug "description"' },
    params: '<description>',
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
  },
  {
    name: 'dash',
    group: 'core',
    description: 'Unified dashboard - status, progress, and roadmap',
    usage: { claude: '/p:dash [view]', terminal: 'prjct dash [view]' },
    params: '[week|month|roadmap|compact]',
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
  },
  {
    name: 'sync',
    group: 'core',
    description: 'Sync project state and update workflow agents',
    usage: { claude: '/p:sync', terminal: 'prjct sync' },
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
  },
  {
    name: 'suggest',
    group: 'core',
    description: 'Smart recommendations based on project state',
    usage: { claude: '/p:suggest', terminal: 'prjct suggest' },
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
  },
  {
    name: 'help',
    group: 'core',
    description: 'Contextual help and guidance',
    usage: { claude: '/p:help [topic]', terminal: 'prjct help [topic]' },
    params: '[topic]',
    implemented: true,
    hasTemplate: true,
    requiresProject: false,
  },

  // ===== OPTIONAL COMMANDS =====
  {
    name: 'design',
    group: 'optional',
    description: 'Design system architecture, APIs, and components',
    usage: { claude: '/p:design [target]', terminal: 'prjct design [target]' },
    params: '[target] --type architecture|api|component',
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    isOptional: true,
  },
  {
    name: 'cleanup',
    group: 'optional',
    description: 'Clean up temp files and old entries',
    usage: { claude: '/p:cleanup', terminal: 'prjct cleanup' },
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    isOptional: true,
  },
  {
    name: 'analyze',
    group: 'optional',
    description: 'Analyze repository and sync tasks',
    usage: { claude: '/p:analyze', terminal: 'prjct analyze' },
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    isOptional: true,
  },
  {
    name: 'undo',
    group: 'optional',
    description: 'Revert to previous snapshot',
    usage: { claude: '/p:undo', terminal: 'prjct undo' },
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    isOptional: true,
    features: ['Git-based snapshots', 'Preserves redo history'],
  },
  {
    name: 'redo',
    group: 'optional',
    description: 'Redo previously undone changes',
    usage: { claude: '/p:redo', terminal: 'prjct redo' },
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    isOptional: true,
  },
  {
    name: 'history',
    group: 'optional',
    description: 'View snapshot history',
    usage: { claude: '/p:history', terminal: 'prjct history' },
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    isOptional: true,
  },
  {
    name: 'recover',
    group: 'optional',
    description: 'Recover abandoned session with context',
    usage: { claude: '/p:recover', terminal: 'prjct recover' },
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    isOptional: true,
  },
  {
    name: 'git',
    group: 'optional',
    description: 'Smart git operations with context',
    usage: { claude: '/p:git [op]', terminal: 'prjct git [op]' },
    params: '[operation]',
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    isOptional: true,
  },
  {
    name: 'test',
    group: 'optional',
    description: 'Run tests with auto-fix',
    usage: { claude: '/p:test', terminal: 'prjct test' },
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    isOptional: true,
  },

  // ===== SETUP COMMANDS =====
  {
    name: 'start',
    group: 'setup',
    description: 'First-time setup (install commands to editors)',
    usage: { claude: null, terminal: 'prjct start' },
    implemented: true,
    hasTemplate: false,
    requiresProject: false,
  },
  {
    name: 'setup',
    group: 'setup',
    description: 'Reconfigure editor installations',
    usage: { claude: '/p:setup', terminal: 'prjct setup' },
    params: '[--force] [--editor <name>]',
    implemented: true,
    hasTemplate: true,
    requiresProject: false,
  },
  {
    name: 'migrate',
    group: 'setup',
    description: 'Migrate project to UUID format + sync',
    usage: { claude: '/p:migrate', terminal: null },
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
  },
  {
    name: 'migrate-all',
    group: 'setup',
    description: 'Migrate all legacy projects to UUID format',
    usage: { claude: '/p:migrate-all', terminal: 'prjct migrate-all' },
    params: '[--deep-scan] [--dry-run]',
    implemented: true,
    hasTemplate: true,
    requiresProject: false,
  },
  {
    name: 'auth',
    group: 'setup',
    description: 'Manage cloud authentication',
    usage: { claude: '/p:auth [action]', terminal: 'prjct auth [action]' },
    params: '[login|logout|status]',
    implemented: true,
    hasTemplate: true,
    requiresProject: false,
  },
]

// Legacy compatibility - category field mapping
export function getCommandsWithCategory(): Array<CommandMeta & { category: string }> {
  return COMMANDS.map(cmd => ({
    ...cmd,
    category: cmd.group, // Map group to category for backward compat
  }))
}
