/**
 * Command Data - Static command definitions and categories
 *
 * Single source of truth for all command metadata.
 * Used by registry for introspection and help display.
 */

import type { CategoryInfo, CommandMeta } from '../types/commands'

// Category definitions
export const CATEGORIES: Record<string, CategoryInfo> = {
  core: {
    title: 'Core Workflow',
    description: '13 essential commands for daily development workflow',
    order: 1,
  },
  optional: {
    title: 'Optional Commands',
    description: 'Advanced features for specialized workflows',
    order: 2,
  },
  setup: {
    title: 'Setup',
    description: 'Installation and configuration (not for daily use)',
    order: 3,
  },
}

// All command definitions
export const COMMANDS: CommandMeta[] = [
  // ===== CORE COMMANDS =====
  {
    name: 'init',
    group: 'core',
    routing: { group: 'planning', method: 'init' },
    description: 'Deep project analysis and initialization',
    usage: { claude: '/p:init "[idea]"', terminal: 'prjct init "[idea]"' },
    params: '[idea]',
    implemented: true,
    hasTemplate: true,
    requiresProject: false,
    requiresLlm: true,
    features: [
      'Architect mode for blank projects',
      'Auto tech stack recommendation',
      'Analyzes existing codebases',
    ],
  },
  {
    name: 'task',
    group: 'core',
    routing: { group: 'workflow', method: 'now' },
    optionSchema: { strings: ['spec'] },
    description: 'Register a task (or show the active one)',
    usage: { claude: '/p:task "<description>"', terminal: 'prjct task "<description>"' },
    params: '[description]',
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    features: [
      'No arg → shows the active task (or none)',
      'Writes to stateStorage; runs before/after workflow rules',
      'Optional Linear issue link when the arg matches `[A-Z]+-\\d+`',
    ],
  },
  {
    name: 'ship',
    group: 'core',
    routing: { group: 'shipping', method: 'ship' },
    optionSchema: { booleans: ['skipHooks', 'noSpecGate', 'noTestGate'], strings: ['intent'] },
    description: 'Commit, push, and celebrate shipped feature',
    usage: { claude: '/p:ship ["feature"]', terminal: 'prjct ship ["feature"]' },
    params: '[feature]',
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    requiresLlm: true,
    features: ['No arg → ships the active task description, or falls back to current work'],
  },
  {
    name: 'sync',
    group: 'core',
    routing: { group: 'analysis', method: 'sync' },
    description: 'Sync project state and update workflow agents',
    usage: { claude: '/p:sync', terminal: 'prjct sync [--package=<name>] [--full]' },
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    requiresLlm: true,
    features: [
      'Incremental sync: only re-analyzes changed files (default)',
      'Force full sync: --full bypasses incremental cache',
      'Monorepo support: --package=<name> for single package sync',
      'Nested PRJCT.md inheritance',
      'Per-package CLAUDE.md generation',
    ],
  },
  {
    name: 'regen',
    group: 'core',
    routing: { group: 'analysis', method: 'regenVault' },
    description: 'Full rebuild of the Obsidian vault for the current project',
    usage: { claude: '/p:regen', terminal: 'prjct regen [--md]' },
    implemented: true,
    hasTemplate: false,
    requiresProject: true,
    requiresLlm: false,
    features: [
      'Nukes `_generated/` and rebuilds from SQLite + CHANGELOG',
      'Use after upgrading prjct-cli to migrate an old vault layout',
      'Idempotent — same output if nothing changed',
    ],
  },
  {
    name: 'suggest',
    group: 'core',
    description: 'Smart recommendations based on project state',
    usage: { claude: '/p:suggest', terminal: 'prjct suggest' },
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    requiresLlm: true,
  },
  {
    name: 'status',
    group: 'core',
    routing: { group: 'primitives', method: 'status' },
    optionSchema: {},
    description: 'Inline status change on the active task (Linear-style escape hatch)',
    usage: { claude: '/p:status <value>', terminal: 'prjct status <value>' },
    params: '[value]',
    implemented: true,
    hasTemplate: false,
    requiresProject: true,
    features: [
      'No args → prints active task + current status',
      'Workflows are the primary status-change mechanism; this is the escape',
    ],
  },
  {
    name: 'tag',
    group: 'core',
    routing: { group: 'primitives', method: 'tag' },
    optionSchema: {},
    description: 'Attach k:v tags to the active task (type:bug, domain:frontend, …)',
    usage: { claude: '/p:tag type:bug', terminal: 'prjct tag type:bug domain:auth' },
    params: '<pairs...>',
    implemented: true,
    hasTemplate: false,
    requiresProject: true,
    features: [
      'Claude decides what to tag — no heuristic classifier',
      'type:<feature|bug|improvement|chore> promotes to tasks.type',
    ],
  },
  {
    name: 'remember',
    group: 'core',
    routing: { group: 'primitives', method: 'remember' },
    optionSchema: { strings: ['tags'] },
    description: 'Capture a project memory entry (fact, decision, learning, gotcha, …)',
    usage: {
      claude: '/p:remember learning "message"',
      terminal: 'prjct remember learning "message" --tags domain:auth',
    },
    params: '<type> "<content>" [--tags k:v,...]',
    implemented: true,
    hasTemplate: false,
    requiresProject: true,
    features: [
      'Types: fact, decision, learning, gotcha, pattern, anti-pattern, shipped, inbox, todo, idea, insight, question, source, person — plus user-defined',
      'Grows the project memory consumable via `prjct context memory`',
    ],
  },
  {
    name: 'forget',
    group: 'core',
    routing: { group: 'primitives', method: 'forget' },
    optionSchema: {},
    description: 'Delete a project memory entry by id (the delete half of `remember`)',
    usage: { claude: 'prjct forget mem_1234', terminal: 'prjct forget mem_1234 [--md]' },
    params: '<id>',
    implemented: true,
    hasTemplate: false,
    requiresProject: true,
    features: [
      'Accepts `mem_1234`, `mem-1234`, or a bare `1234`',
      'Hard-deletes the source event + drops the FTS mirror and any embedding — cannot resurface lexically or semantically',
      'Regenerates the vault so the entry stops surfacing in `.prjct/wiki/_generated/`',
    ],
  },
  {
    name: 'capture',
    group: 'core',
    routing: { group: 'capture', method: 'capture' },
    optionSchema: { strings: ['tags'], booleans: ['force'] },
    description: 'GTD-style universal inbox — dump anything to project memory with zero ceremony',
    usage: {
      claude: '/p:capture "<anything>"',
      terminal: 'prjct capture "call Ana re pricing" --tags domain:sales',
    },
    params: '"<content>" [--tags k:v,...]',
    implemented: true,
    hasTemplate: false,
    requiresProject: true,
    features: [
      'Writes memory type=inbox; Claude retypes later via a clarify workflow',
      'No task id, no branch, no worktree — just persists',
      'Bare `prjct "<text>"` auto-routes to `capture`',
    ],
  },
  {
    name: 'seed',
    group: 'core',
    routing: { group: 'seed', method: 'seed' },
    routingMode: 'bin-only',
    optionSchema: {},
    description: 'Manage declarative packs (persona, memory types, workflow slots, hook signals)',
    usage: {
      claude: '/p:seed list',
      terminal: 'prjct seed add pm,daily',
    },
    params: '[add|remove|list|suggest] [pack,pack,...]',
    implemented: true,
    hasTemplate: false,
    requiresProject: true,
    features: [
      'Packs declare signals only — no bash is written',
      'Add or remove multi-persona contexts per project',
      'Auto-detect suggestion from project stack',
    ],
  },
  {
    name: 'mcp',
    group: 'core',
    routing: { group: 'mcp', method: 'mcp' },
    routingMode: 'bin-only',
    optionSchema: {},
    description:
      'Toggle MCP servers per-project — interactive multi-select in your terminal, list/deny/allow for scripts',
    usage: {
      claude: '/p:mcp list',
      terminal: 'prjct mcp',
    },
    params: '[list|status|deny|allow] [serverName]',
    implemented: true,
    hasTemplate: false,
    requiresProject: false,
    features: [
      'Interactive multi-select with live tool-cost delta (default UX in TTY)',
      'Project-local — writes only to .claude/settings.local.json',
      'Knows the well-known cloud MCPs from claude.ai (PostHog, Atlassian, etc.)',
      'Headless list/deny/allow for LLM agents and scripts (--md flag)',
    ],
  },
  {
    name: 'install',
    group: 'core',
    routing: { group: 'install', method: 'install' },
    routingMode: 'bin-only',
    optionSchema: {},
    description: 'Install Claude Code hooks (~/.claude/settings.json merge-safe)',
    usage: {
      claude: '/p:install',
      terminal: 'prjct install',
    },
    params: '',
    implemented: true,
    hasTemplate: false,
    requiresProject: false,
    features: [
      'Writes 7 passive hooks: SessionStart, UserPromptSubmit, …',
      'Idempotent; existing non-prjct hooks stay intact',
      'Remove with `prjct claude uninstall`',
    ],
  },
  {
    name: 'help',
    group: 'core',
    routingMode: 'bin-only',
    description: 'Contextual help and guidance',
    usage: { claude: '/p:help [topic]', terminal: 'prjct help [topic]' },
    params: '[topic]',
    implemented: true,
    hasTemplate: true,
    requiresProject: false,
  },

  // ===== OPTIONAL COMMANDS =====
  {
    name: 'analysis-save-llm',
    group: 'optional',
    routing: { group: 'analysis', method: 'saveLlmAnalysis' },
    description: 'Persist an analysis JSON blob produced by an LLM run',
    usage: { claude: null, terminal: 'prjct analysis-save-llm <jsonPath>' },
    params: '<jsonPathOrInline>',
    implemented: true,
    hasTemplate: false,
    requiresProject: true,
    isOptional: true,
  },
  {
    name: 'analyze',
    group: 'optional',
    routing: { group: 'analysis', method: 'analyze' },
    description: 'Analyze repository and sync tasks',
    usage: { claude: '/p:analyze', terminal: 'prjct analyze' },
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    isOptional: true,
    requiresLlm: true,
  },
  {
    name: 'git',
    group: 'optional',
    description: 'Smart git operations with context',
    usage: { claude: '/p:git [op]', terminal: 'prjct git [op]' },
    params: '[operation]',
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    isOptional: true,
    requiresLlm: true,
  },
  {
    name: 'test',
    group: 'optional',
    description: 'Run tests with auto-fix',
    usage: { claude: '/p:test', terminal: 'prjct test' },
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    isOptional: true,
    requiresLlm: true,
  },
  {
    name: 'lean',
    group: 'optional',
    routing: { group: 'lean', method: 'lean' },
    optionSchema: {},
    description: 'Anti-over-engineering: set intensity, review/audit/debt (read-only)',
    usage: {
      claude: '/p:lean [review|audit|debt|off|lite|full|ultra]',
      terminal: 'prjct lean [sub]',
    },
    params: '[review|audit|debt|off|lite|full|ultra]',
    implemented: true,
    hasTemplate: false,
    requiresProject: true,
    isOptional: true,
    features: [
      'No arg → show active intensity mode + a one-screen summary',
      'review/audit/debt are advisory — no gate, no source writes',
      'off|lite|full|ultra sets the intensity (mirrors ponytail modes)',
    ],
  },
  {
    name: 'tdd',
    group: 'optional',
    routing: { group: 'tdd', method: 'tdd' },
    optionSchema: {},
    description: 'Test-Driven Development: set intensity, run the test command (check)',
    usage: {
      claude: '/p:tdd [check|off|assist|strict]',
      terminal: 'prjct tdd [sub]',
    },
    params: '[check|off|assist|strict]',
    implemented: true,
    hasTemplate: false,
    requiresProject: true,
    isOptional: true,
    features: [
      'No arg → show mode + the auto-detected test command',
      'off|assist|strict sets the intensity (opt-in, like lean)',
      'check runs the detected test command now (red/green) — the real gate',
    ],
  },
  {
    name: 'sdd',
    group: 'optional',
    routing: { group: 'sdd', method: 'sdd' },
    optionSchema: {},
    description: 'Spec-Driven Development: gate the spec pipeline (off/advisory/strict)',
    usage: {
      claude: '/p:sdd [off|advisory|strict]',
      terminal: 'prjct sdd [sub]',
    },
    params: '[off|advisory|strict]',
    implemented: true,
    hasTemplate: false,
    requiresProject: true,
    isOptional: true,
    features: [
      'No arg → show mode + the active task spec station (pipeline checklist)',
      'off|advisory|strict sets the intensity (opt-in, like lean)',
      'strict: every task needs a reviewed spec; ship blocks unspecced work',
    ],
  },
  {
    name: 'cloud',
    group: 'optional',
    routing: { group: 'cloud', method: 'cloud' },
    optionSchema: {},
    description: 'Cloud sync (paid): link/unlink a project, sync/pull, pause/resume, status',
    usage: {
      claude: '/p:cloud [link|unlink|sync|pull|pause|resume|status]',
      terminal: 'prjct cloud [sub]',
    },
    params: '[link|unlink|sync|pull|pause|resume|status]',
    implemented: true,
    hasTemplate: false,
    requiresProject: true,
    isOptional: true,
    features: [
      'Local-first: nothing leaves the machine until `prjct cloud link`',
      'Token API only — no backend engine details, no client-side paywall',
      'Auto-syncs on `prjct ship` and at session end once linked',
    ],
  },
  {
    name: 'workflow',
    group: 'optional',
    routing: { group: 'workflow', method: 'workflow' },
    optionSchema: {},
    description: 'Configure workflow hooks via natural language',
    usage: { claude: '/p:workflow ["config"]', terminal: 'prjct workflow ["config"]' },
    params: '["natural language config"]',
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    isOptional: true,
    requiresLlm: true,
    features: [
      'Natural language configuration',
      'Before/after hooks for task, done, ship, sync',
      'Permanent, session, or one-time preferences',
    ],
  },
  // ===== SETUP COMMANDS =====
  {
    name: 'start',
    group: 'setup',
    routing: { group: 'setup', method: 'start' },
    routingMode: 'bin-only',
    description: 'First-time setup (install commands to editors)',
    usage: { claude: null, terminal: 'prjct start' },
    implemented: true,
    hasTemplate: false,
    requiresProject: false,
  },
  {
    name: 'setup',
    group: 'setup',
    routing: { group: 'setup', method: 'setup' },
    routingMode: 'bin-only',
    description: 'Reconfigure editor installations',
    usage: { claude: '/p:setup', terminal: 'prjct setup' },
    params: '[--force] [--editor <name>]',
    implemented: true,
    hasTemplate: true,
    requiresProject: false,
  },
  {
    name: 'migrate',
    group: 'setup',
    description: 'Migrate project to UUID format + sync',
    usage: { claude: '/p:migrate', terminal: null },
    implemented: true,
    hasTemplate: true,
    requiresProject: true,
    requiresLlm: true,
  },
  {
    name: 'login',
    group: 'setup',
    routing: { group: 'setup', method: 'login' },
    description: 'Authenticate with prjct cloud (opens browser)',
    usage: { claude: null, terminal: 'prjct login [--url <webUrl>]' },
    params: '[--url <webUrl>]',
    implemented: true,
    hasTemplate: false,
    requiresProject: false,
  },
  {
    name: 'logout',
    group: 'setup',
    routing: { group: 'setup', method: 'logout' },
    description: 'Sign out from prjct cloud',
    usage: { claude: null, terminal: 'prjct logout' },
    implemented: true,
    hasTemplate: false,
    requiresProject: false,
  },
  {
    name: 'auth',
    group: 'setup',
    routing: { group: 'setup', method: 'auth' },
    description: 'Manage cloud authentication',
    usage: { claude: '/p:auth [action]', terminal: 'prjct auth [action]' },
    params: '[login|logout|status]',
    implemented: true,
    hasTemplate: false,
    requiresProject: false,
  },
  {
    name: 'context',
    group: 'setup',
    routing: { group: 'context', method: 'context' },
    routingMode: 'bin-only',
    optionSchema: {},
    description: 'Smart context filtering tools for AI agents',
    usage: { claude: null, terminal: 'prjct context <tool> [args]' },
    params: '<tool> [args]',
    implemented: true,
    hasTemplate: false,
    requiresProject: true,
    features: [
      'files - Find relevant files for a task',
      'signatures - Extract code structure (~90% compression)',
      'imports - Analyze dependency graphs',
      'recent - Find hot files from git history',
      'summary - Intelligent file summarization',
    ],
  },
  {
    name: 'search',
    group: 'core',
    routing: { group: 'context', method: 'search' },
    optionSchema: {},
    description:
      'Search project memory (decisions, learnings, gotchas, ships…) — BM25 + semantic + recall',
    usage: { claude: 'prjct search "<query>"', terminal: 'prjct search "<query>" [--md]' },
    params: '<query>',
    implemented: true,
    hasTemplate: false,
    requiresProject: true,
    features: [
      'Blended retrieval: FTS5 BM25 + opt-in semantic + recency recall',
      'Reranks by proven usefulness, expands one hop of the memory graph',
      '`prjct search mem_1234` resolves a specific entry by id',
    ],
  },
  {
    name: 'update',
    group: 'setup',
    routing: { group: 'update', method: 'update' },
    routingMode: 'bin-only',
    description: 'Update prjct system-wide: package + migrations + daemon restart',
    usage: { claude: null, terminal: 'prjct update [--dry-run]' },
    params: '[--dry-run]',
    implemented: true,
    hasTemplate: false,
    requiresProject: false,
    features: [
      'Phase 1: npm update (migrates homebrew → npm if needed)',
      'Phase 2: All projects — migrate, sweep, reinstall commands',
      'Phase 3: Daemon stop + restart with new code',
      '--dry-run to preview without changes',
    ],
  },
  {
    name: 'uninstall',
    group: 'setup',
    routing: { group: 'uninstall', method: 'uninstall' },
    routingMode: 'bin-only',
    description: 'Complete system removal of prjct',
    usage: { claude: null, terminal: 'prjct uninstall' },
    params: '[--force] [--backup] [--dry-run]',
    implemented: true,
    hasTemplate: false,
    requiresProject: false,
    features: [
      'Removes ~/.prjct-cli/ data',
      'Cleans CLAUDE.md prjct section',
      'Uninstalls Homebrew/npm packages',
      'Backup option before deletion',
    ],
  },
  {
    name: 'team',
    group: 'core',
    routing: { group: 'team', method: 'team' },
    optionSchema: { booleans: ['required', 'enforce'], strings: ['minVersion'] },
    description:
      'Enroll this repo in prjct team mode — commits .prjct/team.json + .claude/CLAUDE.md so teammates pick up shared expectations',
    usage: {
      claude: '/p:team',
      terminal: 'prjct team [--required] [--min-version <semver>]',
    },
    params: '[--required] [--min-version <semver>]',
    implemented: true,
    hasTemplate: false,
    requiresProject: true,
    features: [
      'Writes .prjct/team.json with required/minVersion config',
      'Adds prjct context block to .claude/CLAUDE.md (per-project)',
      'Stages both files for the next commit (does NOT commit)',
      'Teammates clone repo + install prjct → ready to go',
    ],
  },
  {
    name: 'embeddings',
    group: 'core',
    routing: { group: 'embeddings', method: 'embeddings' },
    optionSchema: {
      strings: ['key', 'model', 'baseUrl', 'authHeader', 'authScheme', 'headers', 'query'],
    },
    description:
      'Configure the GLOBAL semantic-embeddings provider (BYOT) — one API key, stored securely, used by every project.',
    usage: {
      claude: '/p:embeddings status',
      terminal:
        'prjct embeddings <set|status|test|clear> [--key <K>] [--model <M>] [--base-url <U>] [--auth-header <H>] [--auth-scheme <S|none>] [--headers "k=v,..."] [--query <qs>]',
    },
    params: '[set|status|test|clear]',
    implemented: true,
    hasTemplate: false,
    requiresProject: false,
    features: [
      'BYOT: bring your own embedding API key — ANY OpenAI-compatible provider',
      'Zero-config: paste just --key, the base URL is auto-detected from its prefix',
      'OpenAI, OpenRouter, Ollama, Together, Mistral, Voyage, Jina, LM Studio…',
      'Non-Bearer providers too: --auth-header api-key --auth-scheme none --query "api-version=..." (Azure OpenAI)',
      'Key stored in the macOS Keychain (else a 0600 file), never in config',
      'Global — applies to all projects; per-project config still overrides',
      'Without a key, recall uses the always-on local subword embedder',
      'Validate with: prjct embeddings test',
    ],
  },
  {
    name: 'guard',
    group: 'core',
    routing: { group: 'guard', method: 'guard' },
    optionSchema: { numbers: ['limit'] },
    description:
      'Surface preventive memory (gotchas, anti-patterns, recurring-bugs) recorded against a file BEFORE you edit it — anticipation, provider-agnostic.',
    usage: {
      claude: '/p:guard <file>',
      terminal: 'prjct guard <file>',
    },
    params: '<file>',
    implemented: true,
    hasTemplate: false,
    requiresProject: true,
    features: [
      'Pillar 3 (anticipation): see the trap before you step in it',
      'Pull, not push — also exposed as the prjct_guard MCP tool for Claude + Codex',
      'Strict: only gotchas / anti-patterns / recurring-bugs — never plain decisions, so no noise',
      'Quiet by design: "clear to edit" when nothing preventive matches',
      'Matches absolute or repo-relative paths by exact / suffix / basename',
    ],
  },
  {
    name: 'config',
    group: 'core',
    routing: { group: 'config', method: 'config' },
    optionSchema: {},
    description: 'Read/write global prjct config — auto-update opt-in, suggestions toggle, etc.',
    usage: {
      claude: '/p:config list',
      terminal: 'prjct config <list|get|set|unset> [key] [value]',
    },
    params: '<list|get|set|unset> [key] [value]',
    implemented: true,
    hasTemplate: false,
    requiresProject: false,
    features: [
      'Stored at ~/.prjct-cli/config/global.json',
      'Opt into silent auto-update: prjct config set auto-update on',
      'Toggle proactive suggestions: prjct config set suggestions off',
      'Booleans accept on/off/true/false; numbers parsed automatically',
    ],
  },
  // ===== SDD: spec-driven development primitives =====
  {
    name: 'spec',
    group: 'core',
    routing: { group: 'spec', method: 'draft' },
    routingMode: 'cold-only',
    description:
      'Draft a spec — Goal/Acceptance/Scope/Risks. The SDD entry point: spec → audit → task → ship.',
    usage: {
      claude: '/p:spec "<title>"',
      terminal: 'prjct spec "<title>" [--goal "..."] [--tags k:v,...]',
    },
    params: '"<title>" [--goal] [--tags]',
    implemented: true,
    hasTemplate: false,
    requiresProject: true,
    features: [
      'Drafting: `prjct spec "<title>"` IS the create action — there is no `draft` subverb (aliases `draft`/`new`/`create` are tolerated and stripped)',
      'Persists in `specs` SQLite table + memory event stream',
      'Renders to ~/Documents/prjct/<slug>/_generated/specs/<slug>.md',
      'Sub-verbs: list, show, update, set-status, record-review, link-task, ship, audit, inventory',
    ],
  },
  {
    name: 'audit-spec',
    group: 'core',
    routing: { group: 'spec', method: 'audit' },
    routingMode: 'cold-only',
    description:
      'Emit subagent dispatch for parallel strategic/architecture/design review of a spec',
    usage: { claude: '/p:audit-spec <id>', terminal: 'prjct audit-spec <id>' },
    params: '<spec-id>',
    implemented: true,
    hasTemplate: false,
    requiresProject: true,
    features: [
      'Emits dispatch prompt — Claude runs three Agent calls in parallel',
      'Each reviewer writes back via `prjct spec record-review`',
      'All three pass → spec auto-promotes draft → reviewed',
    ],
  },

  // ===== BIN-ONLY COMMANDS =====
  // Handled directly in bin/prjct.ts (daemon lifecycle, TTY needs, or
  // process-level concerns). These entries used to exist ONLY as members
  // of the hand-maintained `_binCommands` set — invisible to the registry,
  // help, and the shim-sync derivations. Minimal metadata; `routingMode`
  // is the load-bearing field.
  ...(
    [
      ['daemon', 'Run the prjct daemon in the foreground'],
      ['stop', 'Stop the running prjct daemon'],
      ['restart', 'Restart the prjct daemon'],
      ['upgrade', 'Alias of `prjct update`'],
      ['hook', 'Run a Claude Code hook event (internal; called by the hook scripts)'],
      ['hooks', 'Inspect or reinstall the Claude Code hooks'],
      ['claude', 'Claude Code integration management (install/uninstall)'],
      ['crew', 'Run a crew (multi-subagent) workflow'],
      ['doctor', 'Diagnose the local prjct installation'],
      ['watch', 'Watch project files and react to changes'],
      ['version', 'Print the installed prjct version + provider status'],
      ['prefs', 'Inspect or set workflow preferences'],
      ['retro', 'Summarize what shipped over a time window'],
      ['health', 'Codebase health snapshot'],
      ['skill-adherence', 'Report how well sessions follow the prjct skill'],
      ['review-risk', 'Risk-ranked review hints for the working tree'],
      ['context-save', 'Save the current working context for later restore'],
      ['context-restore', 'Restore a previously saved working context'],
    ] as const
  ).map(
    ([name, description]): CommandMeta => ({
      name,
      group: 'setup',
      description,
      usage: { claude: null, terminal: `prjct ${name}` },
      implemented: true,
      hasTemplate: false,
      requiresProject: false,
      routingMode: 'bin-only',
    })
  ),
]

/** Flag-style aliases resolved in bin/prjct.ts before dispatch. */
export const COMMAND_ALIASES: Record<string, string> = {
  '-h': 'help',
  '--help': 'help',
  '-v': 'version',
  '--version': 'version',
}

/**
 * Commands bin/prjct.ts handles directly — NEVER forwarded to the daemon.
 * Derived from the manifest (plus aliases of bin-only targets); the shim
 * skip-set in scripts/build.js and `_binCommands` in bin/prjct.ts both
 * consume this, so routing is declared in exactly one place.
 */
/**
 * Commands the SHIM must serve cold even though the daemon can handle them
 * when reached via bin/prjct.ts (multi-positional parsing). Consumed by
 * scripts/build.js alongside BIN_ONLY_COMMANDS.
 */
export const COLD_ONLY_COMMANDS: ReadonlySet<string> = new Set(
  COMMANDS.filter((c) => c.routingMode === 'cold-only').map((c) => c.name)
)

export const BIN_ONLY_COMMANDS: ReadonlySet<string> = new Set([
  ...COMMANDS.filter((c) => c.routingMode === 'bin-only').map((c) => c.name),
  ...Object.entries(COMMAND_ALIASES)
    .filter(([, target]) => COMMANDS.some((c) => c.name === target && c.routingMode === 'bin-only'))
    .map(([alias]) => alias),
])
